import { useEffect,useMemo,useState } from 'react';
import { supabase } from '../lib/supabase';
import ListPagination,{useListPagination} from './ui/ListPagination';
const statusLabel={available:'متاح',sold:'مباع',reserved:'محجوز',returned:'مرتجع',damaged:'تالف',transferred:'محوّل'};
export default function ProductSerialsAdmin(){
 const [rows,setRows]=useState([]),[q,setQ]=useState(''),[status,setStatus]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{const {data,error}=await supabase.from('product_serials').select('*,products(id,sku,name,warranty_days)').order('created_at',{ascending:false}).limit(1000);setRows(data||[]);setMsg(error?.message||'')};useEffect(()=>{load()},[]);
 const shown=useMemo(()=>rows.filter(r=>(!status||r.status===status)&&((r.serial_number||'')+' '+(r.products?.name||'')+' '+(r.products?.sku||'')).toLowerCase().includes(q.toLowerCase())),[rows,q,status]);
 const input='rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
 const pager=useListPagination(shown);
 return <div><div className="mb-4 grid gap-3 md:grid-cols-[1fr_240px]"><input className={input} placeholder="بحث بالسريال أو المنتج" value={q} onChange={e=>setQ(e.target.value)}/><select className={input} value={status} onChange={e=>setStatus(e.target.value)}><option value="">كل الحالات</option>{Object.entries(statusLabel).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{msg&&<p className="mb-3 text-xs font-bold text-danger">{msg}</p>}<div className="serials-table-shell overflow-x-auto rounded-2xl border border-border"><table className="serials-table w-full min-w-[760px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">السريال</th><th className="p-3">المنتج</th><th className="p-3">الحالة</th><th className="p-3">ضمان المنتج</th><th className="p-3">تاريخ الإضافة</th></tr></thead><tbody>{pager.visible.map(r=><tr key={r.id} className="border-t border-border"><td data-label="السريال" className="p-3 font-black text-accent">{r.serial_number}</td><td data-label="المنتج" className="p-3"><b>{r.products?.name||'—'}</b><div className="text-xs text-muted">{r.products?.sku||''}</div></td><td data-label="الحالة" className="p-3"><span className="rounded-full border border-border bg-surface px-2 py-1 text-xs font-bold">{statusLabel[r.status]||r.status}</span></td><td data-label="ضمان المنتج" className="p-3">{Number(r.products?.warranty_days||0)>0?`${r.products.warranty_days} يوم`:'بدون ضمان'}</td><td data-label="تاريخ الإضافة" className="p-3 whitespace-nowrap">{new Date(r.created_at).toLocaleDateString('ar-EG')}</td></tr>)}{!shown.length&&<tr><td colSpan="5" className="p-8 text-center text-muted">لا توجد سريلات مطابقة.</td></tr>}</tbody></table></div><ListPagination {...pager}/><p className="mt-3 text-xs leading-6 text-muted">السريلات تُنشأ من مستندات الحركة مثل المشتريات، ولا يتم إنشاء سريال مخزون يدويًا من هذه الشاشة حتى يظل مصدره المحاسبي واضحًا.</p></div>
}