// ألوان كل موديل iPhone. لو الموديل مش هنا → حقل اللون يفضل نص حر.
// ملاحظة: iPhone SE بتجمع ألوان 2020 و2022.
export const MODEL_COLORS = {
  'iPhone X': ['Silver', 'Space Gray'],
  'iPhone XS': ['Silver', 'Space Gray', 'Gold'],
  'iPhone XS Max': ['Silver', 'Space Gray', 'Gold'],
  'iPhone XR': ['Black', 'White', 'Blue', 'Yellow', 'Coral', '(PRODUCT)RED'],
  'iPhone SE': ['Black', 'White', '(PRODUCT)RED', 'Midnight', 'Starlight'],
  'iPhone 11': ['Black', 'White', 'Green', 'Yellow', 'Purple', '(PRODUCT)RED'],
  'iPhone 11 Pro': ['Silver', 'Space Gray', 'Gold', 'Midnight Green'],
  'iPhone 11 Pro Max': ['Silver', 'Space Gray', 'Gold', 'Midnight Green'],
  'iPhone 12 mini': ['Black', 'White', 'Blue', 'Green', 'Purple', '(PRODUCT)RED'],
  'iPhone 12': ['Black', 'White', 'Blue', 'Green', 'Purple', '(PRODUCT)RED'],
  'iPhone 12 Pro': ['Silver', 'Graphite', 'Gold', 'Pacific Blue'],
  'iPhone 12 Pro Max': ['Silver', 'Graphite', 'Gold', 'Pacific Blue'],
  'iPhone 13 mini': ['Midnight', 'Starlight', 'Blue', 'Pink', 'Green', '(PRODUCT)RED'],
  'iPhone 13': ['Midnight', 'Starlight', 'Blue', 'Pink', 'Green', '(PRODUCT)RED'],
  'iPhone 13 Pro': ['Graphite', 'Silver', 'Gold', 'Sierra Blue', 'Alpine Green'],
  'iPhone 13 Pro Max': ['Graphite', 'Silver', 'Gold', 'Sierra Blue', 'Alpine Green'],
  'iPhone 14': ['Midnight', 'Starlight', 'Blue', 'Purple', 'Yellow', '(PRODUCT)RED'],
  'iPhone 14 Plus': ['Midnight', 'Starlight', 'Blue', 'Purple', 'Yellow', '(PRODUCT)RED'],
  'iPhone 14 Pro': ['Space Black', 'Silver', 'Gold', 'Deep Purple'],
  'iPhone 14 Pro Max': ['Space Black', 'Silver', 'Gold', 'Deep Purple'],
  'iPhone 15': ['Black', 'Blue', 'Green', 'Yellow', 'Pink'],
  'iPhone 15 Plus': ['Black', 'Blue', 'Green', 'Yellow', 'Pink'],
  'iPhone 15 Pro': ['Black Titanium', 'White Titanium', 'Blue Titanium', 'Natural Titanium'],
  'iPhone 15 Pro Max': ['Black Titanium', 'White Titanium', 'Blue Titanium', 'Natural Titanium'],
  'iPhone 16': ['Black', 'White', 'Pink', 'Teal', 'Ultramarine'],
  'iPhone 16 Plus': ['Black', 'White', 'Pink', 'Teal', 'Ultramarine'],
  'iPhone 16 Pro': ['Black Titanium', 'White Titanium', 'Natural Titanium', 'Desert Titanium'],
  'iPhone 16 Pro Max': ['Black Titanium', 'White Titanium', 'Natural Titanium', 'Desert Titanium'],
  'iPhone 17': ['Black', 'White', 'Mist Blue', 'Lavender', 'Sage'],
  'iPhone 17 Air': ['Black', 'Silver', 'Sky Blue', 'Light Gold'],
  'iPhone 17 Pro': ['Silver', 'Deep Blue', 'Cosmic Orange'],
  'iPhone 17 Pro Max': ['Silver', 'Deep Blue', 'Cosmic Orange'],
};
