import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import { useAllowedBranches } from '../hooks/useAllowedBranches';

const TYPES={
 sales:{title:'تقارير المبيعات',table:'sales_invoices',date:'invoice_date',select:'id,invoice_number,invoice_date,branch,status,customer_name,total,paid',cols:['رقم الفاتورة','التاريخ','الفرع','العميل','الحالة','الإجمالي','المدفوع']},
 purchases:{title:'تقارير المشتريات',table:'purchase_invoices',date:'invoice_date',select:'id,invoice_number,invoice_date,branch,status,total,paid,suppliers(name)',cols:['رقم الفاتورة','التاريخ','الفرع','المورد','الحالة','الإجمالي','المدفوع']},
 inventory:{title:'تقارير المخزون',table:'product_movements',date:'created_at',select:'id,created_at,branch,movement_type,quantity,reference_type,reference_id,products(sku,name)',cols:['التاريخ','الفرع','SKU','الصنف','نوع الحركة','الكمية','المرجع']},
 finance:{title:'التقارير المالية',table:'financial_movements',date:'movement_date',select:'id,movement_number,movement_date,movement_type,amount,party_name,reference_type,reference_id,treasuries(name,branch)',cols:['رقم الحركة','التاريخ','الخزينة','الفرع','النوع','الطرف','المبلغ']},
};
const money=n=>Number(n||0).toLocaleString('ar-EG',{minimumFractionDigits:2,maximumFractionDigits:2});
const status=s=>({draft:'مسودة',posted:'مرحّل',cancelled:'ملغي'}[s]||s||'—');
const movement=t=>({sale:'بيع',purchase:'شراء',purchase_return:'مرتجع شراء',sales_return:'مرتجع بيع',transfer_in:'تحويل وارد',transfer_out:'تحويل صادر',adjustment_in:'تسوية إضافة',adjustment_out:'تسوية خصم',receipt:'قبض',payment:'صرف'}[t]||t||'—');

export default function ERPReportsAdmin({type='sales'}){
 const {branches:allowedBranches,canAccessBranch,canSeeAllBranches}=useAllowedBranches();
 const cfg=TYPES[type]||TYPES.sales; const [rows,setRows]=useState([]),[loading,setLoading]=useState(true),[msg,setMsg]=useState('');
 const [from,setFrom]=useState(''),[to,setTo]=useState(''),[branch,setBranch]=useState('');
 const load=async()=>{setLoading(true);setMsg('');let q=supabase.from(cfg.table).select(cfg.select).order(cfg.date,{ascending:false}).limit(2000);if(from)q=q.gte(cfg.date,from);if(to)q=q.lte(cfg.date,type==='inventory'?`${to}T23:59:59.999Z`:to);const {data,error}=await q;if(error)setMsg(error.message);setRows((data||[]).filter(r=>canSeeAllBranches||canAccessBranch(type==='finance'?r.treasuries?.branch:r.branch)));setLoading(false)};
 useEffect(()=>{load()},[type]);
 const branches=useMemo(()=>allowedBranches.length?allowedBranches:[...new Set(rows.map(r=>type==='finance'?(r.treasuries?.branch||''):r.branch).filter(Boolean))].sort(),[allowedBranches,rows,type]);
 const filtered=useMemo(()=>branch?rows.filter(r=>(type==='finance'?r.treasuries?.branch:r.branch)===branch):rows,[rows,branch,type]);
 const total=useMemo(()=>type==='inventory'?filtered.reduce((s,r)=>s+Number(r.quantity||0),0):filtered.reduce((s,r)=>s+Number(r.total??r.amount??0),0),[filtered,type]);
 const cells=r=> type==='sales'?[r.invoice_number,r.invoice_date,r.branch||'—',r.customer_name||'نقدي',status(r.status),money(r.total),money(r.paid)] : type==='purchases'?[r.invoice_number,r.invoice_date,r.branch||'—',r.suppliers?.name||'—',status(r.status),money(r.total),money(r.paid)] : type==='inventory'?[new Date(r.created_at).toLocaleString('ar-EG'),r.branch||'—',r.products?.sku||'—',r.products?.name||'—',movement(r.movement_type),r.quantity,`${r.reference_type||'—'} ${r.reference_id||''}`] : [r.movement_number,r.movement_date,r.treasuries?.name||'—',r.treasuries?.branch||'—',movement(r.movement_type),r.party_name||'—',money(r.amount)];
 const print=()=>window.print();
 const csv=()=>{const esc=v=>`"${String(v??'').replaceAll('"','""')}"`;const text='\ufeff'+[cfg.cols,...filtered.map(cells)].map(x=>x.map(esc).join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));a.download=`${cfg.title}.csv`;a.click();URL.revokeObjectURL(a.href)};
 const input='rounded-xl border border-border bg-surface px-3 py-2 text-sm text-text outline-none focus:border-accent';
 return <div className="space-y-4"><div className="flex flex-wrap items-end gap-2"><label className="text-xs font-bold text-muted">من<input type="date" className={`${input} mt-1 block`} value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="text-xs font-bold text-muted">إلى<input type="date" className={`${input} mt-1 block`} value={to} onChange={e=>setTo(e.target.value)}/></label><select className={input} value={branch} onChange={e=>setBranch(e.target.value)}><option value="">كل الفروع</option>{branches.map(b=><option key={b}>{b}</option>)}</select><button onClick={load} className="rounded-xl bg-accent px-4 py-2 text-sm font-black text-on-accent">تطبيق</button><button onClick={csv} className="rounded-xl border border-border px-4 py-2 text-sm font-bold">CSV</button><button onClick={print} className="rounded-xl border border-border px-4 py-2 text-sm font-bold">طباعة</button></div><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-border bg-surface p-3"><div className="text-xs text-muted">عدد السجلات</div><b className="text-xl text-accent">{filtered.length}</b></div><div className="rounded-xl border border-border bg-surface p-3"><div className="text-xs text-muted">{type==='inventory'?'إجمالي كميات الحركات':'الإجمالي'}</div><b className="text-xl text-accent">{type==='inventory'?total:money(total)}</b></div></div>{msg&&<p className="text-sm font-bold text-danger">{msg}</p>}{loading?<div className="h-40 animate-pulse rounded-2xl bg-surface"/>:<div className="overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[850px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr>{cfg.cols.map(c=><th key={c} className="p-3">{c}</th>)}</tr></thead><tbody>{filtered.map(r=><tr key={r.id} className="border-t border-border">{cells(r).map((c,i)=><td key={i} className="p-3">{c}</td>)}</tr>)}{!filtered.length&&<tr><td colSpan={cfg.cols.length} className="p-8 text-center text-muted">لا توجد بيانات مطابقة.</td></tr>}</tbody></table></div>}</div>;
}
