import { useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { supabase } from '../lib/supabase';
import InvoiceQuickView from './InvoiceQuickView';

const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const dateOf=v=>String(v||'').slice(0,10);
const within=(d,a,b)=>(!a||d>=a)&&(!b||d<=b);

export default function PartyStatementAdmin({type='customer',initialPartyId=''}){
 const isCustomer=type==='customer';
 const [parties,setParties]=useState([]),[partyId,setPartyId]=useState(String(initialPartyId||'')),[from,setFrom]=useState(''),[to,setTo]=useState(''),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[msg,setMsg]=useState(''),[invoiceView,setInvoiceView]=useState(null);
 useEffect(()=>{supabase.from(isCustomer?'customers':'suppliers').select(isCustomer?'id,display_name,business_name,opening_balance':'id,name,business_name,opening_balance').order(isCustomer?'display_name':'name').then(({data,error})=>error?setMsg(error.message):setParties(data||[]))},[isCustomer]);
 const party=parties.find(x=>String(x.id)===partyId), partyName=party?(isCustomer?party.display_name:party.name):'';
 const load=async()=>{if(!partyId)return setMsg(`اختر ${isCustomer?'العميل':'المورد'}.`);setLoading(true);setMsg('');try{const id=Number(partyId);let entries=[];const opening=Number(party?.opening_balance||0);if(opening)entries.push({date:'0000-00-00',kind:'opening',number:'OPENING',description:'رصيد افتتاحي',debit:isCustomer?opening:0,credit:isCustomer?0:opening});
  if(isCustomer){const [{data:inv,error:ie},{data:ret,error:re},{data:mov,error:me}]=await Promise.all([supabase.from('sales_invoices').select('id,invoice_number,invoice_date,total,paid,status,created_at').eq('customer_id',id).eq('status','posted'),supabase.from('sales_returns').select('id,return_number,return_date,total,refund_amount,status,created_at').eq('customer_id',id).eq('status','posted'),supabase.from('financial_movements').select('id,movement_number,movement_date,movement_type,amount,reference_id,notes,created_at').eq('party_type','customer').eq('party_id',id)]);if(ie)throw ie;if(re)throw re;if(me)throw me;(inv||[]).forEach(x=>entries.push({date:dateOf(x.invoice_date||x.created_at),kind:'invoice',invoiceId:x.id,invoiceType:'sales',number:x.invoice_number,description:'فاتورة مبيعات',debit:Number(x.total),credit:Number(x.paid||0)}));(ret||[]).forEach(x=>entries.push({date:dateOf(x.return_date||x.created_at),kind:'return',number:x.return_number,description:'مرتجع مبيعات',debit:0,credit:Number(x.total||0)}));(mov||[]).forEach(x=>entries.push({date:dateOf(x.movement_date||x.created_at),kind:'movement',number:x.movement_number,description:x.movement_type==='receipt'?'سند قبض':x.movement_type==='payment'?'سند صرف':'حركة مالية',debit:x.movement_type==='payment'?Number(x.amount):0,credit:x.movement_type==='receipt'?Number(x.amount):0}));
  }else{const [{data:inv,error:ie},{data:ret,error:re},{data:mov,error:me}]=await Promise.all([supabase.from('purchase_invoices').select('id,invoice_number,invoice_date,total,paid,status,created_at').eq('supplier_id',id).eq('status','posted'),supabase.from('purchase_returns').select('id,return_number,return_date,total,status,created_at').eq('supplier_id',id).eq('status','posted'),supabase.from('financial_movements').select('id,movement_number,movement_date,movement_type,amount,reference_id,notes,created_at').eq('party_type','supplier').eq('party_id',id)]);if(ie)throw ie;if(re)throw re;if(me)throw me;(inv||[]).forEach(x=>entries.push({date:dateOf(x.invoice_date||x.created_at),kind:'invoice',invoiceId:x.id,invoiceType:'purchases',number:x.invoice_number,description:'فاتورة مشتريات',debit:Number(x.paid||0),credit:Number(x.total)}));(ret||[]).forEach(x=>entries.push({date:dateOf(x.return_date||x.created_at),kind:'return',number:x.return_number,description:'مرتجع مشتريات',debit:Number(x.total||0),credit:0}));(mov||[]).forEach(x=>entries.push({date:dateOf(x.movement_date||x.created_at),kind:'movement',number:x.movement_number,description:x.movement_type==='payment'?'سند صرف':x.movement_type==='receipt'?'سند قبض':'حركة مالية',debit:x.movement_type==='payment'?Number(x.amount):0,credit:x.movement_type==='receipt'?Number(x.amount):0}));}
  entries=entries.filter(x=>x.kind==='opening'||within(x.date,from,to)).sort((a,b)=>a.date.localeCompare(b.date));let balance=0;entries=entries.map(x=>{balance+=Number(x.debit)-Number(x.credit);return {...x,balance}});setRows(entries);
 }catch(e){setMsg(e.message)}finally{setLoading(false)}};
 useEffect(()=>{setRows([])},[partyId,type]);
 const totals=useMemo(()=>rows.reduce((a,x)=>({debit:a.debit+x.debit,credit:a.credit+x.credit}),{debit:0,credit:0}),[rows]), balance=rows.at(-1)?.balance||0;
 const exportExcel=()=>{if(!rows.length)return;const data=rows.map(x=>({'التاريخ':x.kind==='opening'?'افتتاحي':x.date,'المستند':x.number,'البيان':x.description,'مدين':x.debit,'دائن':x.credit,'الرصيد':x.balance}));const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'كشف الحساب');XLSX.writeFile(wb,`كشف_حساب_${partyName||type}.xlsx`)};
 const input='rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
 return <div className="space-y-4"><div className="rounded-2xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-black text-text">كشف حساب {isCustomer?'عميل':'مورد'}</h3><p className="mt-1 text-xs text-muted">الرصيد الافتتاحي + الفواتير + المرتجعات + الحركات المالية المرتبطة بالطرف.</p></div><div className="flex gap-2"><button onClick={exportExcel} disabled={!rows.length} className="rounded-xl border border-border px-3 py-2 text-xs font-black disabled:opacity-40">تصدير Excel</button><button onClick={()=>window.print()} disabled={!rows.length} className="rounded-xl border border-border px-3 py-2 text-xs font-black disabled:opacity-40">طباعة</button></div></div><div className="mt-4 grid gap-3 md:grid-cols-4"><select className={input} value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">اختر {isCustomer?'العميل':'المورد'} *</option>{parties.map(p=><option key={p.id} value={p.id}>{isCustomer?p.display_name:p.name}{p.business_name?` — ${p.business_name}`:''}</option>)}</select><input className={input} type="date" value={from} onChange={e=>setFrom(e.target.value)}/><input className={input} type="date" value={to} onChange={e=>setTo(e.target.value)}/><button onClick={load} disabled={loading} className="rounded-xl bg-accent px-4 py-2.5 text-sm font-black text-on-accent">{loading?'جارٍ التحميل…':'عرض كشف الحساب'}</button></div>{msg&&<p className="mt-3 text-xs font-bold text-accent">{msg}</p>}</div>
 {rows.length>0&&<><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-4"><div className="text-xs text-muted">إجمالي المدين</div><div className="mt-1 text-xl font-black">{money(totals.debit)}</div></div><div className="rounded-2xl border border-border bg-card p-4"><div className="text-xs text-muted">إجمالي الدائن</div><div className="mt-1 text-xl font-black">{money(totals.credit)}</div></div><div className="rounded-2xl border border-accent-line bg-accent-soft p-4"><div className="text-xs text-muted">الرصيد الحالي</div><div className="mt-1 text-xl font-black text-accent">{money(Math.abs(balance))} <span className="text-xs">{balance===0?'مسدد':isCustomer?(balance>0?'لنا على العميل':'للعميل علينا'):(balance<0?'للمورد علينا':'لنا على المورد')}</span></div></div></div>
 <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-4"><b>{partyName}</b>{party?.business_name&&<span className="mr-2 text-xs text-muted">· {party.business_name}</span>}</div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">التاريخ</th><th className="p-3">المستند</th><th className="p-3">البيان</th><th className="p-3">مدين</th><th className="p-3">دائن</th><th className="p-3">الرصيد</th></tr></thead><tbody>{rows.map((x,i)=><tr key={`${x.number}-${i}`} className="border-t border-border"><td className="p-3">{x.kind==='opening'?'افتتاحي':x.date}</td><td className="p-3 font-bold text-accent">{x.kind==='invoice'?<button type="button" onClick={()=>setInvoiceView({id:x.invoiceId,type:x.invoiceType})} className="underline underline-offset-4 hover:opacity-75" title="فتح الفاتورة ومراجعتها">{x.number}</button>:x.number}</td><td className="p-3">{x.description}</td><td className="p-3">{x.debit?money(x.debit):'—'}</td><td className="p-3">{x.credit?money(x.credit):'—'}</td><td className="p-3 font-black">{money(x.balance)}</td></tr>)}</tbody></table></div></section></>}
 {invoiceView&&<InvoiceQuickView type={invoiceView.type} invoiceId={invoiceView.id} onClose={()=>setInvoiceView(null)}/>}
 </div>
}
