import { useEffect,useMemo,useState } from 'react';
import { supabase } from '../lib/supabase';
import ListPagination,{useListPagination} from './ui/ListPagination';

const typeLabel={purchase:'شراء',purchase_return:'مرتجع شراء',sale:'بيع',sale_return:'مرتجع بيع',transfer_in:'تحويل وارد',transfer_out:'تحويل صادر',adjustment_in:'تسوية إضافة',adjustment_out:'تسوية خصم',opening:'رصيد افتتاحي'};
export default function ProductMovementsAdmin(){
 const [rows,setRows]=useState([]),[products,setProducts]=useState([]),[q,setQ]=useState(''),[product,setProduct]=useState(''),[msg,setMsg]=useState('');
 const load=async()=>{setMsg('');const [{data:r,error},{data:p}]=await Promise.all([supabase.from('product_movements').select('*,products(id,sku,name),product_serials(serial_number)').order('created_at',{ascending:false}).limit(500),supabase.from('products').select('id,sku,name').order('name')]);if(error)setMsg(error.message);setRows(r||[]);setProducts(p||[])};useEffect(()=>{load()},[]);
 const shown=useMemo(()=>rows.filter(r=>(!product||String(r.product_id)===product)&&((r.products?.name||'')+' '+(r.products?.sku||'')+' '+(r.product_serials?.serial_number||'')+' '+(r.reference_id||'')+' '+(r.branch||'')).toLowerCase().includes(q.toLowerCase())),[rows,q,product]);
 const signed=r=>['sale','purchase_return','transfer_out','adjustment_out'].includes(r.movement_type)?-Number(r.quantity||0):Number(r.quantity||0);
 const balance=shown.reduce((s,r)=>s+signed(r),0);
 const input='rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
 const pager=useListPagination(shown);
 return <div><div className="mb-4 grid gap-3 md:grid-cols-[1fr_280px_auto]"><input className={input} placeholder="بحث بالصنف أو السريال أو المرجع أو الفرع" value={q} onChange={e=>setQ(e.target.value)}/><select className={input} value={product} onChange={e=>setProduct(e.target.value)}><option value="">كل المنتجات</option>{products.map(p=><option key={p.id} value={p.id}>{p.sku} — {p.name}</option>)}</select><div className="rounded-xl border border-border bg-surface px-4 py-2 text-center"><div className="text-[11px] text-muted">صافي الكمية المعروضة</div><b className="text-accent">{balance}</b></div></div>{msg&&<p className="mb-3 text-xs font-bold text-danger">{msg}</p>}<div className="overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[980px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">التاريخ</th><th className="p-3">الصنف</th><th className="p-3">الحركة</th><th className="p-3">الكمية</th><th className="p-3">السريال</th><th className="p-3">الفرع</th><th className="p-3">المرجع</th><th className="p-3">ملاحظات</th></tr></thead><tbody>{pager.visible.map(r=><tr key={r.id} className="border-t border-border"><td className="p-3 whitespace-nowrap">{new Date(r.created_at).toLocaleString('ar-EG')}</td><td className="p-3"><b>{r.products?.name||'—'}</b><div className="text-xs text-muted">{r.products?.sku||''}</div></td><td className="p-3">{typeLabel[r.movement_type]||r.movement_type}</td><td className={`p-3 font-black ${signed(r)<0?'text-danger':'text-accent'}`}>{signed(r)>0?'+':''}{signed(r)}</td><td className="p-3">{r.product_serials?.serial_number||'—'}</td><td className="p-3">{r.branch||'—'}</td><td className="p-3">{r.reference_type||'—'}{r.reference_id?` · ${r.reference_id}`:''}</td><td className="p-3">{r.notes||'—'}</td></tr>)}{!shown.length&&<tr><td colSpan="8" className="p-8 text-center text-muted">لا توجد حركات مطابقة.</td></tr>}</tbody></table></div><ListPagination {...pager}/></div>
}