import {useEffect,useMemo,useState} from 'react';
import { useAllowedBranches } from '../hooks/useAllowedBranches';
import {supabase} from '../lib/supabase';
import {usePermissions} from '../context/PermissionContext';
import {auditERP} from '../lib/erpAudit';
import {postReturnAccounting} from '../lib/erpAccounting';
const I='w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text';
export default function PurchaseReturnsAdmin(){const{canAccessBranch}=useAllowedBranches();
 const {can}=usePermissions(); const [invoices,setInvoices]=useState([]),[invoice,setInvoice]=useState(''),[qty,setQty]=useState({}),[serials,setSerials]=useState({}),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[treasuries,setTreasuries]=useState([]),[settlementType,setSettlementType]=useState('cash'),[treasury,setTreasury]=useState('');
 useEffect(()=>{supabase.from('treasuries').select('id,name,branch').eq('is_active',true).order('name').then(({data})=>setTreasuries((data||[]).filter(x=>!x.branch||canAccessBranch(x.branch))));supabase.from('purchase_invoices').select('*,suppliers(name),purchase_invoice_items(*,products(name,sku,serial_tracked))').eq('status','posted').order('created_at',{ascending:false}).then(({data})=>setInvoices((data||[]).filter(x=>canAccessBranch(x.branch))))},[]);
 const inv=invoices.find(x=>String(x.id)===invoice); const selected=useMemo(()=>inv?.purchase_invoice_items?.filter(x=>Number(qty[x.id]||0)>0)||[],[inv,qty]);
 const total=selected.reduce((s,x)=>s+Number(qty[x.id])*Number(x.unit_cost),0);
 const post=async()=>{if(!can('can_erp_purchase_return'))return setMsg('ليس لديك صلاحية ترحيل المستندات.');setBusy(true);setMsg('');try{if(!inv)throw Error('اختر فاتورة شراء.');if(settlementType==='cash'&&!treasury)throw Error('حدد الخزينة المستلمة من المورد.');if(!selected.length)throw Error('حدد كمية مرتجعة.');const lines=selected.map(x=>{let q=Number(qty[x.id]),ss=x.products?.serial_tracked?(serials[x.id]||'').split(/[\n,]+/).map(s=>s.trim()).filter(Boolean):[];return{item_id:x.id,quantity:q,serial_numbers:ss}});const{data,error}=await supabase.rpc('post_purchase_return_tx',{p_invoice_id:inv.id,p_items:lines,p_settlement_type:settlementType,p_treasury_id:settlementType==='cash'?Number(treasury):null});if(error)throw error;setQty({});setSerials({});setMsg(`تم ترحيل مرتجع الشراء ${data?.number||''} كعملية مخزنية ومحاسبية واحدة.`)}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 return <div className="rounded-2xl border border-border p-4"><h3 className="font-black">مرتجع مشتريات</h3><p className="mt-1 text-xs text-muted">المرتجع مرتبط بفاتورة شراء مُرحّلة ويخصم الكميات من مخزون نفس الفرع.</p><select className={`${I} mt-3`} value={invoice} onChange={e=>{setInvoice(e.target.value);setQty({});setSerials({})}}><option value="">اختر فاتورة شراء</option>{invoices.map(x=><option key={x.id} value={x.id}>{x.invoice_number} · {x.suppliers?.name||'مورد'}</option>)}</select>{inv?.purchase_invoice_items?.map(x=><div className="mt-2 grid gap-2 md:grid-cols-[1fr_130px_1fr]" key={x.id}><div className="py-2">{x.products?.name} · المشترى {x.quantity}</div><input className={I} type="number" min="0" max={x.quantity} step={x.products?.serial_tracked?'1':'0.001'} value={qty[x.id]||''} onChange={e=>setQty({...qty,[x.id]:e.target.value})} placeholder="المرتجع"/><textarea className={I} disabled={!x.products?.serial_tracked} value={serials[x.id]||''} onChange={e=>setSerials({...serials,[x.id]:e.target.value})} placeholder={x.products?.serial_tracked?'السريلات المرتجعة':'غير متتبع بالسريال'}/></div>)}<div className="mt-3 grid gap-2 md:grid-cols-2"><select className={I} value={settlementType} onChange={e=>{setSettlementType(e.target.value);setTreasury('')}}><option value="cash">رد نقدي من المورد</option><option value="credit">على حساب المورد</option></select>{settlementType==='cash'&&<select className={I} value={treasury} onChange={e=>setTreasury(e.target.value)}><option value="">الخزينة المستلمة *</option>{treasuries.filter(t=>!t.branch||t.branch===inv?.branch).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>}</div>{inv&&<div className="mt-3 font-black">إجمالي المرتجع: {total.toLocaleString()}</div>}<button disabled={busy||!can('can_erp_purchase_return')} onClick={post} className="mt-3 rounded-xl bg-accent px-5 py-2.5 font-black text-on-accent disabled:opacity-50">{busy?'جارٍ الترحيل...':'ترحيل المرتجع'}</button>{msg&&<p className="mt-2 text-sm font-bold text-accent">{msg}</p>}</div>
}
