import { Fragment, useEffect, useMemo, useState } from 'react';
import * as XLSX from 'xlsx';
import { supabase } from '../lib/supabase';
import InvoiceQuickView from './InvoiceQuickView';
import ERPDocumentViewer from './ERPDocumentViewer';
import { usePermissions } from '../context/PermissionContext';

const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});
const dateOf=v=>String(v||'').slice(0,10);
const within=(d,a,b)=>(!a||d>=a)&&(!b||d<=b);
const input='w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text';

export default function PartyStatementAdmin({type='customer',initialPartyId=''}){
 const isCustomer=type==='customer';
 const {can}=usePermissions(); const canPrint=can('can_erp_document_print');
 const [parties,setParties]=useState([]),[partyId,setPartyId]=useState(String(initialPartyId||'')),[datePreset,setDatePreset]=useState(''),[detailed,setDetailed]=useState(false),[from,setFrom]=useState(''),[to,setTo]=useState(''),[rows,setRows]=useState([]),[details,setDetails]=useState({}),[loading,setLoading]=useState(false),[msg,setMsg]=useState(''),[invoiceView,setInvoiceView]=useState(null),[documentView,setDocumentView]=useState(null);
 useEffect(()=>{supabase.from(isCustomer?'customers':'suppliers').select(isCustomer?'id,display_name,business_name,opening_balance':'id,name,business_name,opening_balance').order(isCustomer?'display_name':'name').then(({data,error})=>error?setMsg(error.message):setParties(data||[]))},[isCustomer]);
 const party=parties.find(x=>String(x.id)===partyId), partyName=party?(isCustomer?party.display_name:party.name):'';
 const localDate=d=>{const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)};
 const applyDatePreset=v=>{setDatePreset(v);const now=new Date(),today=new Date(now.getFullYear(),now.getMonth(),now.getDate());let a='',b='';
  if(v==='today'){a=b=localDate(today)}
  else if(v==='yesterday'){const d=new Date(today);d.setDate(d.getDate()-1);a=b=localDate(d)}
  else if(v==='last7'){const d=new Date(today);d.setDate(d.getDate()-6);a=localDate(d);b=localDate(today)}
  else if(v==='thisMonth'){a=localDate(new Date(today.getFullYear(),today.getMonth(),1));b=localDate(today)}
  else if(v==='lastMonth'){a=localDate(new Date(today.getFullYear(),today.getMonth()-1,1));b=localDate(new Date(today.getFullYear(),today.getMonth(),0))}
  else if(v==='last365'){const d=new Date(today);d.setDate(d.getDate()-364);a=localDate(d);b=localDate(today)}
  else if(v==='thisYear'){a=localDate(new Date(today.getFullYear(),0,1));b=localDate(today)}
  else if(v!=='custom'){a='';b=''}
  setFrom(a);setTo(b);setRows([]);
 };

 const load=async()=>{if(!partyId)return setMsg(`اختر ${isCustomer?'العميل':'المورد'}.`);setLoading(true);setMsg('');try{const id=Number(partyId);let entries=[];const opening=Number(party?.opening_balance||0);if(opening)entries.push({date:'0000-00-00',kind:'opening',number:'OPENING',description:'رصيد افتتاحي',debit:isCustomer?opening:0,credit:isCustomer?0:opening});
  if(isCustomer){const [{data:inv,error:ie},{data:ret,error:re},{data:mov,error:me}]=await Promise.all([supabase.from('sales_invoices').select('id,invoice_number,invoice_date,total,paid,status,created_at').eq('customer_id',id).eq('status','posted'),supabase.from('sales_returns').select('id,return_number,return_date,total,refund_amount,status,created_at').eq('customer_id',id).eq('status','posted'),supabase.from('financial_movements').select('id,movement_number,movement_date,movement_type,amount,reference_id,notes,created_at').eq('party_type','customer').eq('party_id',id)]);if(ie)throw ie;if(re)throw re;if(me)throw me;(inv||[]).forEach(x=>entries.push({date:dateOf(x.invoice_date||x.created_at),kind:'invoice',invoiceId:x.id,invoiceType:'sales',number:x.invoice_number,description:'فاتورة مبيعات',debit:Number(x.total),credit:Number(x.paid||0)}));(ret||[]).forEach(x=>entries.push({date:dateOf(x.return_date||x.created_at),kind:'return',returnId:x.id,returnType:'sales_return',number:x.return_number,description:'مرتجع مبيعات',debit:0,credit:Number(x.total||0)}));(mov||[]).forEach(x=>entries.push({date:dateOf(x.movement_date||x.created_at),kind:'movement',movementId:x.id,number:x.movement_number,description:x.movement_type==='receipt'?'سند قبض':x.movement_type==='payment'?'سند صرف':'حركة مالية',debit:x.movement_type==='payment'?Number(x.amount):0,credit:x.movement_type==='receipt'?Number(x.amount):0}));
  }else{const [{data:inv,error:ie},{data:ret,error:re},{data:mov,error:me}]=await Promise.all([supabase.from('purchase_invoices').select('id,invoice_number,invoice_date,total,paid,status,created_at').eq('supplier_id',id).eq('status','posted'),supabase.from('purchase_returns').select('id,return_number,return_date,total,status,created_at').eq('supplier_id',id).eq('status','posted'),supabase.from('financial_movements').select('id,movement_number,movement_date,movement_type,amount,reference_id,notes,created_at').eq('party_type','supplier').eq('party_id',id)]);if(ie)throw ie;if(re)throw re;if(me)throw me;(inv||[]).forEach(x=>entries.push({date:dateOf(x.invoice_date||x.created_at),kind:'invoice',invoiceId:x.id,invoiceType:'purchases',number:x.invoice_number,description:'فاتورة مشتريات',debit:Number(x.paid||0),credit:Number(x.total)}));(ret||[]).forEach(x=>entries.push({date:dateOf(x.return_date||x.created_at),kind:'return',returnId:x.id,returnType:'purchase_return',number:x.return_number,description:'مرتجع مشتريات',debit:Number(x.total||0),credit:0}));(mov||[]).forEach(x=>entries.push({date:dateOf(x.movement_date||x.created_at),kind:'movement',movementId:x.id,number:x.movement_number,description:x.movement_type==='payment'?'سند صرف':x.movement_type==='receipt'?'سند قبض':'حركة مالية',debit:x.movement_type==='payment'?Number(x.amount):0,credit:x.movement_type==='receipt'?Number(x.amount):0}));}
  entries=entries.filter(x=>x.kind==='opening'||within(x.date,from,to)).sort((a,b)=>a.date.localeCompare(b.date));let balance=0;entries=entries.map(x=>{balance+=Number(x.debit)-Number(x.credit);return {...x,balance}});setRows(entries);
  if(detailed){const dmap={};const groups=[['sales','sales_invoice_items','invoice_id',entries.filter(x=>x.invoiceType==='sales').map(x=>x.invoiceId)],['purchases','purchase_invoice_items','invoice_id',entries.filter(x=>x.invoiceType==='purchases').map(x=>x.invoiceId)],['sales_return','sales_return_items','return_id',entries.filter(x=>x.returnType==='sales_return').map(x=>x.returnId)],['purchase_return','purchase_return_items','return_id',entries.filter(x=>x.returnType==='purchase_return').map(x=>x.returnId)]];for(const[g,t,f,ids0]of groups){const ids=ids0.filter(Boolean);if(ids.length){const{data}=await supabase.from(t).select('*,products(name,sku)').in(f,ids);(data||[]).forEach(v=>(dmap[`${g}:${v[f]}`]??=[]).push(v))}}setDetails(dmap)}else setDetails({});
 }catch(e){setMsg(e.message)}finally{setLoading(false)}};
 useEffect(()=>{setRows([])},[partyId,type]);
 const totals=useMemo(()=>rows.reduce((a,x)=>({debit:a.debit+x.debit,credit:a.credit+x.credit}),{debit:0,credit:0}),[rows]), balance=rows.at(-1)?.balance||0;

 const exportExcel=()=>{if(!rows.length)return;const data=[];rows.forEach(x=>{data.push({'التاريخ':x.kind==='opening'?'افتتاحي':x.date,'المستند':x.number,'البيان':x.description,'الصنف':'','الكمية':'','سعر الوحدة':'','الخصم':'','مدين':x.debit,'دائن':x.credit,'الرصيد':x.balance});if(detailed){const key=x.invoiceId?`${x.invoiceType}:${x.invoiceId}`:x.returnId?`${x.returnType}:${x.returnId}`:'';(details[key]||[]).forEach(v=>data.push({'التاريخ':'','المستند':'','البيان':'↳ تفاصيل المستند','الصنف':`${v.products?.sku?`${v.products.sku} · `:''}${v.products?.name||'—'}`,'الكمية':v.quantity??'','سعر الوحدة':v.unit_price??v.unit_cost??'','الخصم':v.discount??0,'مدين':'','دائن':'','الرصيد':''}))}});const ws=XLSX.utils.json_to_sheet(data),wb=XLSX.utils.book_new();ws['!cols']=[{wch:14},{wch:20},{wch:28},{wch:34},{wch:10},{wch:14},{wch:12},{wch:14},{wch:14},{wch:16}];ws['!autofilter']={ref:ws['!ref']||'A1:J1'};ws['!views']=[{rightToLeft:true}];const rg=XLSX.utils.decode_range(ws['!ref']||'A1:A1');for(let R=1;R<=rg.e.r;R++){for(const C of [7,8,9]){const cell=ws[XLSX.utils.encode_cell({r:R,c:C})];if(cell&&typeof cell.v==='number')cell.z='#,##0.00';}}XLSX.utils.book_append_sheet(wb,ws,'كشف الحساب');if(!wb.Workbook)wb.Workbook={};wb.Workbook.Views=[{RTL:true}];const bytes=XLSX.write(wb,{bookType:'xlsx',type:'array'}),blob=new Blob([bytes],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`كشف_حساب_${partyName||type}.xlsx`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500)};
 const printStatement=()=>{
 if(!rows.length)return;if(!canPrint)return setMsg('لا تملك صلاحية طباعة كشف الحساب.');
 const totals=rows.reduce((a,x)=>({debit:a.debit+Number(x.debit||0),credit:a.credit+Number(x.credit||0)}),{debit:0,credit:0}),closing=rows.length?Number(rows[rows.length-1].balance||0):0,periodLabel=dateOptions.find(x=>x.value===datePreset)?.label||'كل الفترات';
 const body=rows.map(x=>{const key=x.invoiceId?`${x.invoiceType}:${x.invoiceId}`:x.returnId?`${x.returnType}:${x.returnId}`:'';const itemRows=detailed?(details[key]||[]).map((v,i)=>`<tr class="detail"><td></td><td></td><td colspan="4"><b>${i+1}. ${v.products?.sku?`${v.products.sku} · `:''}${v.products?.name||'—'}</b> | الكمية: ${v.quantity??'—'} | سعر الوحدة: ${money(v.unit_price??v.unit_cost)}${Number(v.discount||0)?` | الخصم: ${money(v.discount)}`:''}</td></tr>`).join(''):'';return `<tr><td>${x.kind==='opening'?'افتتاحي':x.date}</td><td>${x.number||''}</td><td>${x.description||''}</td><td>${x.debit?money(x.debit):'—'}</td><td>${x.credit?money(x.credit):'—'}</td><td class="bal">${money(x.balance)}</td></tr>${itemRows}`}).join('');
 const html=`<!doctype html><html dir="rtl" lang="ar"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>كشف حساب</title><style>@page{size:A4 portrait;margin:12mm}*{box-sizing:border-box}html,body{margin:0;background:#fff;color:#111;font-family:Arial,Tahoma,sans-serif;direction:rtl}body{font-size:11px}.sheet{width:100%;max-width:186mm;margin:auto}.head{display:flex;justify-content:space-between;border-bottom:2px solid #111;padding-bottom:9px;margin-bottom:11px}.brand{font-size:20px;font-weight:900}.sub,.muted{color:#666}.title{text-align:left}.title h1{font-size:18px;margin:0 0 4px}.party{border:1px solid #bbb;border-radius:8px;padding:9px 11px;display:flex;justify-content:space-between;margin-bottom:10px}.party b{font-size:14px}.summary{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;margin-bottom:12px}.card{border:1px solid #bbb;border-radius:8px;padding:8px;text-align:center}.card span{display:block;color:#666;margin-bottom:4px}.card b{font-size:15px}table{width:100%;border-collapse:collapse;table-layout:fixed}th,td{border:1px solid #aaa;padding:6px 5px;vertical-align:top;word-break:break-word}th{background:#eee;text-align:center}th:nth-child(1){width:14%}th:nth-child(2){width:18%}th:nth-child(3){width:26%}th:nth-child(4),th:nth-child(5),th:nth-child(6){width:14%}td:nth-child(4),td:nth-child(5),td:nth-child(6){text-align:center;direction:ltr}.bal{font-weight:900}.detail td{background:#f7f7f7}.foot{margin-top:9px;padding-top:7px;border-top:1px solid #bbb;color:#666;font-size:9px;display:flex;justify-content:space-between}@media print{thead{display:table-header-group}tr{break-inside:avoid;page-break-inside:avoid}}</style></head><body><main class="sheet"><div class="head"><div><div class="brand">iShop ERP</div><div class="sub">نظام إدارة الأعمال</div></div><div class="title"><h1>كشف حساب ${isCustomer?'عميل':'مورد'}${detailed?' تفصيلي':''}</h1><div>${periodLabel}</div></div></div><div class="party"><div><span class="muted">${isCustomer?'العميل':'المورد'}</span><br><b>${partyName||'—'}</b></div><div><span class="muted">الفترة</span><br><b>${periodLabel}${datePreset==='custom'?` · ${from||'—'} إلى ${to||'—'}`:''}</b></div></div><div class="summary"><div class="card"><span>إجمالي المدين</span><b>${money(totals.debit)}</b></div><div class="card"><span>إجمالي الدائن</span><b>${money(totals.credit)}</b></div><div class="card"><span>الرصيد</span><b>${money(closing)}</b></div></div><table><thead><tr><th>التاريخ</th><th>المستند</th><th>البيان</th><th>مدين</th><th>دائن</th><th>الرصيد</th></tr></thead><tbody>${body}</tbody></table><div class="foot"><span>تم إنشاء الكشف من iShop ERP</span><span>${new Date().toLocaleString('ar-EG')}</span></div></main></body></html>`;
 const w=window.open('','_blank');if(!w){setMsg('المتصفح منع نافذة الطباعة. اسمح بالنوافذ المنبثقة لهذا الموقع ثم أعد المحاولة.');return}try{w.document.open();w.document.write(html);w.document.close();const doPrint=()=>{try{w.focus();w.print()}catch(e){setMsg('تعذر تشغيل الطباعة: '+(e?.message||e))}};if(w.document.readyState==='complete')setTimeout(doPrint,150);else w.addEventListener('load',()=>setTimeout(doPrint,150),{once:true})}catch(e){try{w.close()}catch{}setMsg('تعذر تجهيز كشف الحساب للطباعة: '+(e?.message||e))}
};
 return <div className="space-y-4"><div className="rounded-2xl border border-border bg-card p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><h3 className="text-lg font-black text-text">كشف حساب {isCustomer?'عميل':'مورد'}</h3><p className="mt-1 text-xs text-muted">الرصيد الافتتاحي + الفواتير + المرتجعات + الحركات المالية المرتبطة بالطرف.</p></div><div className="flex gap-2"><button onClick={exportExcel} disabled={!rows.length} className="rounded-xl border border-border px-3 py-2 text-xs font-black disabled:opacity-40">تصدير Excel</button><button type="button" onClick={printStatement} disabled={!rows.length} title={canPrint?'طباعة كشف الحساب':'تحتاج صلاحية طباعة المستندات'} className="rounded-xl border border-border px-3 py-2 text-xs font-black disabled:opacity-40">🖨️ طباعة</button></div></div><div className="mt-4 grid gap-3 md:grid-cols-4"><select className={input} value={partyId} onChange={e=>setPartyId(e.target.value)}><option value="">اختر {isCustomer?'العميل':'المورد'} *</option>{parties.map(p=><option key={p.id} value={p.id}>{isCustomer?p.display_name:p.name}{p.business_name?` — ${p.business_name}`:''}</option>)}</select><select className={input} value={datePreset} onChange={e=>applyDatePreset(e.target.value)}><option value="">كل الفترات</option><option value="today">اليوم</option><option value="yesterday">الأمس</option><option value="last7">آخر 7 أيام</option><option value="thisMonth">الشهر الحالي</option><option value="lastMonth">الشهر الماضي</option><option value="last365">آخر 365 يوم</option><option value="thisYear">هذه السنة</option><option value="custom">نطاق مخصص</option></select>{datePreset==='custom'&&<><input className={input} type="date" aria-label="من" value={from} onChange={e=>{setFrom(e.target.value);setRows([])}}/><input className={input} type="date" aria-label="إلى" value={to} onChange={e=>{setTo(e.target.value);setRows([])}}/></>}<label className="flex cursor-pointer items-center justify-between gap-3 rounded-xl border border-border bg-surface px-4 py-2.5 text-sm font-black"><span>كشف حساب تفصيلي</span><input type="checkbox" checked={detailed} onChange={e=>{setDetailed(e.target.checked);setRows([]);setDetails({})}} className="size-5 rounded-full accent-current"/></label><button onClick={load} disabled={loading} className="rounded-xl bg-accent px-4 py-2.5 text-sm font-black text-on-accent">{loading?'جارٍ التحميل…':'عرض كشف الحساب'}</button></div>{msg&&<p className="mt-3 text-xs font-bold text-accent">{msg}</p>}</div>
 {rows.length>0&&<><div className="grid gap-3 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-4"><div className="text-xs text-muted">إجمالي المدين</div><div className="mt-1 text-xl font-black">{money(totals.debit)}</div></div><div className="rounded-2xl border border-border bg-card p-4"><div className="text-xs text-muted">إجمالي الدائن</div><div className="mt-1 text-xl font-black">{money(totals.credit)}</div></div><div className="rounded-2xl border border-accent-line bg-accent-soft p-4"><div className="text-xs text-muted">الرصيد الحالي</div><div className="mt-1 text-xl font-black text-accent">{money(Math.abs(balance))} <span className="text-xs">{balance===0?'مسدد':isCustomer?(balance>0?'لنا على العميل':'للعميل علينا'):(balance<0?'للمورد علينا':'لنا على المورد')}</span></div></div></div>
 <section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-4"><b>{partyName}</b>{party?.business_name&&<span className="mr-2 text-xs text-muted">· {party.business_name}</span>}</div><div className="overflow-x-auto"><table className="w-full min-w-[800px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">التاريخ</th><th className="p-3">المستند</th><th className="p-3">البيان</th><th className="p-3">مدين</th><th className="p-3">دائن</th><th className="p-3">الرصيد</th></tr></thead><tbody>{rows.map((x,i)=><Fragment key={`${x.number}-${i}`}><tr className="border-t border-border"><td className="p-3">{x.kind==='opening'?'افتتاحي':x.date}</td><td className="p-3 font-bold text-accent">{x.kind==='invoice'?<button type="button" onClick={()=>setDocumentView({id:x.invoiceId,type:x.invoiceType==='sales'?'sales_invoice':'purchase_invoice'})} className="underline underline-offset-4 hover:opacity-75">{x.number}</button>:x.kind==='return'?<button type="button" onClick={()=>setDocumentView({id:x.returnId,type:x.returnType})} className="underline underline-offset-4 hover:opacity-75">{x.number}</button>:x.kind==='movement'?<button type="button" onClick={()=>setDocumentView({id:x.movementId,type:isCustomer?'customer_collection':'supplier_payment'})} className="underline underline-offset-4 hover:opacity-75">{x.number}</button>:x.number}</td><td className="p-3">{x.description}</td><td className="p-3">{x.debit?money(x.debit):'—'}</td><td className="p-3">{x.credit?money(x.credit):'—'}</td><td className="p-3 font-black">{money(x.balance)}</td></tr>{detailed&&(()=>{const key=x.invoiceId?`${x.invoiceType}:${x.invoiceId}`:x.returnId?`${x.returnType}:${x.returnId}`:'';const list=details[key]||[];return list.length?<tr className="bg-surface/60"><td></td><td></td><td colSpan="4" className="p-2"><div className="overflow-hidden rounded-xl border border-border"><table className="w-full text-xs"><thead><tr className="text-muted"><th className="p-2 text-right">الصنف</th><th>الكمية</th><th>سعر الوحدة</th><th>الخصم</th><th>الإجمالي</th></tr></thead><tbody>{list.map((v,n)=><tr key={v.id||n} className="border-t border-border"><td className="p-2">{v.products?.sku?`${v.products.sku} · `:''}{v.products?.name||'—'}</td><td>{v.quantity??'—'}</td><td>{money(v.unit_price??v.unit_cost)}</td><td>{money(v.discount||0)}</td><td>{money(v.line_total??(Number(v.quantity||0)*Number((v.unit_price ?? v.unit_cost) || 0)-Number(v.discount||0)))}</td></tr>)}</tbody></table></div></td></tr>:null})()}</Fragment>)}</tbody></table></div></section></>}
 {documentView&&<ERPDocumentViewer type={documentView.type} id={documentView.id} onClose={()=>setDocumentView(null)}/>} 
 </div>
}
