import{useEffect,useMemo,useRef,useState}from'react';
import{supabase}from'../lib/supabase';
import{publicMediaUrl}from'../lib/productMedia';
import ProductSmartSearch from'./ui/ProductSmartSearch';
import{hasPositiveStock,productMatches}from'../lib/productSearch';
import{fetchAllProductMovements}from'../lib/inventoryData';
import{useAllowedBranches}from'../hooks/useAllowedBranches';
import PartySmartSearch from'./ui/PartySmartSearch';
import PartyPaymentsAdmin from'./PartyPaymentsAdmin';
import PartyStatementAdmin from'./PartyStatementAdmin';
import PartyAccountSummary from'./ui/PartyAccountSummary';
import BarcodeScanner from'./BarcodeScanner';
import InvoiceQuickView from'./InvoiceQuickView';
import{useAuth}from'../context/AuthContext';
import{playSystemSound}from'../lib/soundSettings';
const I='w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text';
const money=n=>Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2});

function SearchableFilter({items,value,onChange,allLabel,placeholder}){
 const selected=items.find(x=>String(x.id)===String(value));
 const[text,setText]=useState(selected?.name||''),[open,setOpen]=useState(false);
 useEffect(()=>{setText(items.find(x=>String(x.id)===String(value))?.name||'')},[value,items]);
 const needle=text.trim().toLocaleLowerCase('ar');
 const matches=items.filter(x=>!needle||String(x.name||'').toLocaleLowerCase('ar').includes(needle)).slice(0,12);
 const choose=x=>{onChange(x?String(x.id):'');setText(x?.name||'');setOpen(false)};
 return <div className="relative min-w-0 w-full">
  <input className={I} value={text} onFocus={()=>setOpen(true)} onChange={e=>{setText(e.target.value);setOpen(true);if(!e.target.value)onChange('')}} onBlur={()=>setTimeout(()=>setOpen(false),160)} placeholder={placeholder}/>
  {open&&<div className="absolute z-[230] mt-1 max-h-64 w-full min-w-0 overflow-y-auto rounded-xl border border-border bg-card p-1 shadow-2xl">
   <button type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>choose(null)} className="block w-full rounded-lg px-3 py-2 text-right text-sm font-black hover:bg-surface">{allLabel}</button>
   {matches.map(x=><button key={x.id} type="button" onMouseDown={e=>e.preventDefault()} onClick={()=>choose(x)} className="block w-full rounded-lg px-3 py-2 text-right text-sm hover:bg-surface">{x.name}</button>)}
   {needle&&!matches.length&&<div className="px-3 py-3 text-center text-xs text-muted">لا توجد نتائج مطابقة. اكتب جزءًا آخر من الاسم.</div>}
  </div>}
 </div>
}
const stockQty=(movements,id,branch)=>Number((movements||[]).filter(m=>String(m.product_id)===String(id)&&m.branch===branch).reduce((s,m)=>{const q=Number(m.quantity||0),t=String(m.movement_type||'').toLowerCase();return s+(['purchase','transfer_in','adjustment_in','sale_return','opening','opening_stock'].includes(t)?q:['sale','transfer_out','adjustment_out','purchase_return'].includes(t)?-q:q)},0).toFixed(3));
export default function PointOfSale({onExit, activeShift=null, onOpenShiftReport=null}){
 const{branches,canAccessBranch,canSeeAllBranches}=useAllowedBranches();
 const{username,userRow}=useAuth();
 const[products,setProducts]=useState([]),[movements,setMovements]=useState([]),[cats,setCats]=useState([]),[brands,setBrands]=useState([]),[customers,setCustomers]=useState([]),[cart,setCart]=useState([]),[q,setQ]=useState(''),[cat,setCat]=useState(''),[brand,setBrand]=useState(''),[branch,setBranch]=useState(''),[customer,setCustomer]=useState(''),[paymentType,setPaymentType]=useState('cash'),[treasury,setTreasury]=useState(''),[treasuries,setTreasuries]=useState([]),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[partyModal,setPartyModal]=useState(''),[newCustomer,setNewCustomer]=useState({display_name:'',phone:''}),[serialPicker,setSerialPicker]=useState(null),[serialQuery,setSerialQuery]=useState(''),[serialRows,setSerialRows]=useState([]),[serialScan,setSerialScan]=useState(false),[success,setSuccess]=useState(null),[printId,setPrintId]=useState(null),[galleryOpen,setGalleryOpen]=useState(false),[differentQty,setDifferentQty]=useState(false),[stage,setStage]=useState(1);
 const productInputRef=useRef(null),qtyRefs=useRef(new Map());
 const load=async()=>{const[a,b,c,d,e,m]=await Promise.all([supabase.from('products').select('id,name,sku,barcode,images,category_id,brand_id,serial_tracked,warranty_days,sale_price').eq('is_active',true).order('name'),supabase.from('product_categories').select('id,name').eq('is_active',true),supabase.from('product_brands').select('id,name').eq('is_active',true).order('name'),supabase.from('customers').select('id,display_name,phone').order('display_name'),supabase.from('treasuries').select('id,name,branch,opening_balance').eq('is_active',true).order('name'),fetchAllProductMovements('id,product_id,serial_id,movement_type,quantity,branch,created_at')]);setProducts(a.data||[]);setCats(b.data||[]);setBrands(c.data||[]);setCustomers(d.data||[]);setTreasuries(e.data||[]);setMovements(m||[])};
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);
 useEffect(()=>{if(!branch&&branches.length)setBranch(branches[0])},[branches,branch]);
 const saveCustomer=async()=>{if(!newCustomer.display_name.trim())return setMsg('اسم العميل مطلوب.');const{data,error}=await supabase.from('customers').insert({display_name:newCustomer.display_name.trim(),phone:newCustomer.phone.trim()||null,source:'manual'}).select('id,display_name,phone').single();if(error)return setMsg(error.message);setCustomers(v=>[...v,data].sort((a,b)=>a.display_name.localeCompare(b.display_name)));setCustomer(String(data.id));setNewCustomer({display_name:'',phone:''});setPartyModal('')};
 const available=branch?products.filter(p=>hasPositiveStock(movements,p.id,branch)):[];
 const shown=available.filter(p=>(!cat||String(p.category_id)===cat)&&(!brand||String(p.brand_id)===brand)&&productMatches(p,q));
 const total=useMemo(()=>cart.reduce((s,x)=>s+x.qty*Number(x.price||0),0),[cart]),itemCount=cart.length,pieceCount=cart.reduce((s,x)=>s+Number(x.qty||0),0);
 const focusProduct=()=>setTimeout(()=>{const el=productInputRef.current;if(el){el.focus({preventScroll:true});try{el.setSelectionRange?.(0,el.value.length)}catch{}}},80);
 const focusQty=id=>setTimeout(()=>{const el=qtyRefs.current.get(String(id));if(el){el.scrollIntoView({block:'nearest',behavior:'smooth'});el.focus({preventScroll:true});el.select?.()}},100);
 const add=p=>{const current=cart.find(a=>String(a.id)===String(p.id)),max=stockQty(movements,p.id,branch);if(max<=0||Number(current?.qty||0)>=max){setMsg(`لا توجد كمية إضافية متاحة من ${p.name}.`);return false}setCart(v=>{const x=v.find(a=>String(a.id)===String(p.id));return x?v.map(a=>String(a.id)===String(p.id)?{...a,qty:Math.min(max,Number(a.qty||0)+1)}:a):[...v,{...p,qty:1,price:Number(p.sale_price||0),serials:[]}]});playSystemSound('itemAdd');return true};
 const addFromSearch=p=>{if(!add(p))return false;setQ('');setMsg(`تمت إضافة ${p.name} إلى الفاتورة ✓`);if(differentQty)focusQty(p.id);else focusProduct();return true};
 const openSerials=async x=>{setSerialPicker(x.id);setSerialQuery('');const{data,error}=await supabase.from('product_serials').select('id,serial_number,status,product_id').eq('product_id',x.id).eq('status','available').order('serial_number');if(error)return setMsg(error.message);const ids=new Set((movements||[]).filter(m=>m.branch===branch&&String(m.product_id)===String(x.id)&&m.serial_id).map(m=>String(m.serial_id)));setSerialRows((data||[]).filter(s=>ids.has(String(s.id))))};
 const chooseSerial=sn=>{setCart(v=>v.map(x=>x.id===serialPicker&&!x.serials.includes(sn)?{...x,serials:[...x.serials,sn]}:x));setSerialQuery('')};
 const customerBalance=async id=>{if(!id)return 0;const[{data:p},{data:inv},{data:ret},{data:mov}]=await Promise.all([supabase.from('customers').select('opening_balance').eq('id',id).maybeSingle(),supabase.from('sales_invoices').select('total,paid').eq('customer_id',id).eq('status','posted'),supabase.from('sales_returns').select('total').eq('customer_id',id).eq('status','posted'),supabase.from('financial_movements').select('movement_type,amount').eq('party_type','customer').eq('party_id',id).neq('status','cancelled')]);let b=Number(p?.opening_balance||0);(inv||[]).forEach(x=>b+=Number(x.total||0)-Number(x.paid||0));(ret||[]).forEach(x=>b-=Number(x.total||0));(mov||[]).forEach(x=>b+=x.movement_type==='receipt'?-Number(x.amount||0):x.movement_type==='payment'?Number(x.amount||0):0);return b};
 const treasuryBalance=async id=>{if(!id)return null;const t=treasuries.find(x=>String(x.id)===String(id));const{data}=await supabase.from('financial_movements').select('movement_type,amount,status').eq('treasury_id',id);return(data||[]).reduce((b,m)=>m.status==='cancelled'?b:b+(m.movement_type==='receipt'||m.movement_type==='transfer_in'?Number(m.amount||0):-Number(m.amount||0)),Number(t?.opening_balance||0))};
 const checkout=async()=>{try{setBusy(true);setMsg('');if(!branch)throw Error('حدد الفرع / المخزن.');if(!canAccessBranch(branch))throw Error('ليس لديك صلاحية على هذا الفرع.');if(paymentType==='cash'&&!treasury)throw Error('حدد الخزينة المستلمة.');if(paymentType==='credit'&&!customer)throw Error('العميل إجباري للبيع الآجل.');if(!cart.length)throw Error('السلة فارغة.');let c=customers.find(x=>String(x.id)===customer),num=`POS-${Date.now()}`;const lines=cart.map(x=>{const ss=x.serials||[],qty=Number(x.qty);if(Number(x.price)<0||qty<=0)throw Error('راجع السعر والكمية.');if(stockQty(movements,x.id,branch)<qty)throw Error(`الكمية المطلوبة من ${x.name} أكبر من رصيد الفرع.`);if(x.serial_tracked&&ss.length!==qty)throw Error(`اختر ${qty} سيريال للصنف ${x.name}.`);return{product_id:x.id,quantity:qty,unit_price:Number(x.price),serial_numbers:ss,warranty_days:x.warranty_days||0}});const header={invoice_number:num,customer_id:c?.id||null,customer_name:c?.display_name||'نقدي',customer_phone:c?.phone||null,branch,payment_type:paymentType,treasury_id:paymentType==='cash'?Number(treasury):null,invoice_date:new Date().toISOString().slice(0,10),subtotal:total,discount:0,total,notes:'نقطة البيع'};
  let data=null,error=null;({data,error}=await supabase.rpc('post_sales_invoice_tx',{p_header:header,p_items:lines}));
  if(error&&/load failed|failed to fetch|network/i.test(String(error.message||error))){await new Promise(r=>setTimeout(r,900));const verify=await supabase.from('sales_invoices').select('id,invoice_number').eq('invoice_number',num).maybeSingle();if(verify.data){data={id:verify.data.id,number:verify.data.invoice_number};error=null}else{({data,error}=await supabase.rpc('post_sales_invoice_tx',{p_header:header,p_items:lines}));if(error&&/duplicate key|invoice_number/i.test(String(error.message||error))){const again=await supabase.from('sales_invoices').select('id,invoice_number').eq('invoice_number',num).maybeSingle();if(again.data){data={id:again.data.id,number:again.data.invoice_number};error=null}}}}
  if(error)throw error;const savedNumber=data?.number||data?.invoice_number||num;let savedId=data?.id||data?.invoice_id||null;if(!savedId){const f=await supabase.from('sales_invoices').select('id').eq('invoice_number',savedNumber).maybeSingle();savedId=f.data?.id||null}const[cb,tb]=await Promise.all([customer?customerBalance(Number(customer)):Promise.resolve(0),paymentType==='cash'?treasuryBalance(Number(treasury)):Promise.resolve(null)]);setSuccess({number:savedNumber,id:savedId,items:itemCount,pieces:pieceCount,customer:c?.display_name||'عميل نقدي',customerBalance:cb,payment:paymentType==='cash'?'نقدي / مدفوع':'آجل',treasuryBalance:tb});setCart([]);setQ('');await load()}catch(e){const raw=String(e?.message||e||'');setMsg(/load failed|failed to fetch|network/i.test(raw)?'تعذر الاتصال بالخادم. لم يتم تأكيد البيع. تحقق من الإنترنت ثم أعد المحاولة؛ النظام يمنع تكرار نفس الفاتورة تلقائيًا.':raw)}finally{setBusy(false)}};
 const selectedCustomer=customers.find(x=>String(x.id)===String(customer));
 const currentUserName=userRow?.display_name||userRow?.full_name||username||'المستخدم';
 const goStage=n=>{setStage(n);setTimeout(()=>window.scrollTo({top:0,behavior:'smooth'}),30)};
 const backStage=()=>goStage(Math.max(1,stage-1));
 const activeSerialProduct=cart.find(x=>x.id===serialPicker),serialSuggestions=serialRows.filter(s=>String(s.serial_number).includes(serialQuery.trim())&&!activeSerialProduct?.serials.includes(s.serial_number)).slice(0,12);
 return <div dir="rtl" className="min-h-[100dvh] w-full max-w-full overflow-x-hidden bg-bg px-3 pb-[max(1rem,env(safe-area-inset-bottom))] pt-[max(.75rem,env(safe-area-inset-top))] sm:px-5"><div className="mx-auto w-full max-w-6xl min-w-0 space-y-4">
 <div className="sticky top-0 z-40 rounded-2xl border border-accent-line bg-card/95 p-2.5 shadow-lg backdrop-blur">
  <div className="grid min-w-0 grid-cols-2 gap-2 text-[11px] sm:flex sm:items-center sm:overflow-x-auto sm:text-xs">
   <button type="button" onClick={()=>onExit?.()} className="min-w-0 rounded-xl border border-border px-3 py-2 font-black">✕ خروج</button><button type="button" onClick={backStage} disabled={stage===1} className="min-w-0 rounded-xl border border-border px-3 py-2 font-black disabled:opacity-30">← السابق</button>{onOpenShiftReport&&<button type="button" onClick={onOpenShiftReport} className="min-w-0 rounded-xl border border-accent-line bg-accent-soft px-3 py-2 font-black text-accent">📈 الوردية</button>}
   <div className="min-w-0 rounded-xl bg-surface px-3 py-2"><span className="text-muted">👤 المستخدم</span><b className="mr-1 block sm:inline">{currentUserName}</b></div>
   <button type="button" onClick={()=>goStage(1)} className="min-w-0 rounded-xl bg-surface px-3 py-2 text-right"><span className="text-muted">🏬 الفرع</span><b className="mr-1 block text-accent sm:inline">{branch||'—'}</b></button>
   <button type="button" onClick={()=>goStage(1)} className="min-w-0 rounded-xl bg-surface px-3 py-2 text-right"><span className="text-muted">👤 العميل</span><b className="mr-1 block text-accent sm:inline">{selectedCustomer?.display_name||'نقدي'}</b></button>
   <button type="button" onClick={()=>branch&&goStage(2)} className="min-w-0 rounded-xl bg-surface px-3 py-2 text-right"><span className="text-muted">🛒 الفاتورة</span><b className="mr-1 block text-accent sm:inline">{pieceCount} قطعة</b></button>
   <div className="col-span-2 min-w-0 rounded-xl border border-accent-line bg-accent-soft px-3 py-2 text-center font-black text-accent sm:col-span-1">{stage}/4 · {stage===1?'الأساسيات':stage===2?'إضافة الأصناف':stage===3?'المراجعة':'الدفع'}</div>
  </div>
 </div>

 <section className={`${stage===1?'block':'hidden'} rounded-2xl border-2 border-accent-line bg-card p-4`}>
  <div className="mb-4"><h2 className="text-lg font-black text-accent">1. أساسيات الفاتورة</h2><p className="text-xs text-muted">حدد الفرع والعميل قبل إضافة الأصناف.</p></div>
  <div className="grid gap-4 lg:grid-cols-2">
   <div className="rounded-2xl border border-border bg-surface p-4"><label className="mb-2 block text-sm font-black">🏬 الفرع</label>{canSeeAllBranches?<select className={I} value={branch} onChange={e=>{setBranch(e.target.value);setTreasury('');setCart([]);setQ('')}}><option value="">اختر الفرع / المخزن *</option>{branches.map(b=><option key={b} value={b}>{b}</option>)}</select>:<div className="rounded-xl border border-border bg-card px-4 py-3"><span className="text-xs text-muted">الفرع المخصص للمستخدم</span><b className="mt-1 block text-accent">{branch||'جارٍ التحميل…'}</b></div>}</div>
   <div className="rounded-2xl border border-border bg-surface p-4"><label className="mb-2 block text-sm font-black">👤 العميل</label><div className="grid grid-cols-[minmax(0,1fr)_auto] gap-2"><PartySmartSearch parties={customers} type="customer" value={customer} onSelect={c=>setCustomer(c?String(c.id):'')} placeholder="عميل نقدي — ابحث باسم العميل"/><button type="button" onClick={()=>setPartyModal('add')} className="rounded-xl border border-border px-4 text-xl font-black">＋</button></div>{customer?<div className="mt-3 space-y-2"><PartyAccountSummary type="customer" partyId={customer}/><div className="grid grid-cols-2 gap-2"><button type="button" onClick={()=>setPartyModal('statement')} className="rounded-xl border border-accent-line bg-accent-soft px-3 py-3 text-xs font-black text-accent">📄 كشف الحساب</button><button type="button" onClick={()=>setPartyModal('pay')} className="rounded-xl border border-accent-line bg-accent-soft px-3 py-3 text-xs font-black text-accent">💵 تحصيل</button></div></div>:<div className="mt-3 rounded-xl border border-dashed border-border p-3 text-xs text-muted">يمكن المتابعة كعميل نقدي، أو اختيار عميل لعرض بياناته وكشف حسابه والتحصيل.</div>}</div>
  </div>
  <button type="button" disabled={!branch} onClick={()=>goStage(2)} className="mt-4 w-full rounded-xl bg-accent px-4 py-3 font-black text-on-accent disabled:opacity-40">متابعة لإضافة الأصناف ←</button>
 </section>

 <section className={`${stage===2?'block':'hidden'} rounded-2xl border-2 border-accent-line bg-card p-4`}>
  <div className="mb-3"><h2 className="text-lg font-black text-accent">2. إضافة الأصناف</h2><p className="text-xs text-muted">ابحث أو امسح الباركود، وستظهر الأصناف داخل جدول الفاتورة.</p></div>
  <ProductSmartSearch products={available} getStock={p=>stockQty(movements,p.id,branch)} value={q} onChange={setQ} onSelect={addFromSearch} inputRef={productInputRef} clearOnSelect disabled={!branch} placeholder={branch?'بحث بالاسم / SKU / الباركود — يدعم القارئ والكاميرا':'اختر الفرع أولًا'}/>
  <div className="mt-3 grid min-w-0 grid-cols-2 gap-2 pb-1 sm:grid-cols-4"><SearchableFilter items={cats} value={cat} onChange={setCat} allLabel="كل الأقسام" placeholder="ابحث بجزء من اسم القسم"/><SearchableFilter items={brands} value={brand} onChange={setBrand} allLabel="كل العلامات التجارية" placeholder="ابحث بجزء من اسم العلامة"/><button type="button" onClick={()=>setGalleryOpen(true)} disabled={!branch} className="min-w-0 rounded-xl border border-accent-line bg-accent-soft px-3 py-2 text-xs font-black text-accent">▦ عرض بالصور</button><button type="button" aria-pressed={differentQty} onClick={()=>{setDifferentQty(v=>!v);focusProduct()}} className={`min-w-0 rounded-xl border px-3 py-2 text-xs font-black ${differentQty?'border-accent bg-accent text-on-accent':'border-border bg-surface text-text'}`}>◉ كميات مختلفة</button></div>
  <div className="mt-4 min-w-0 overflow-hidden rounded-2xl border-2 border-accent-line bg-surface"><div className="min-w-0"><div className="grid grid-cols-[26px_minmax(0,1fr)_52px_64px_70px_24px] sm:grid-cols-[42px_minmax(180px,1fr)_78px_100px_110px_36px] gap-1 sm:gap-2 border-b border-border bg-card px-2 py-2 text-center text-[10px] font-black text-muted"><span>م</span><span className="text-right">الصنف</span><span>الكمية</span><span>السعر</span><span>الإجمالي</span><span></span></div><div className="max-h-[38vh] min-h-[180px] overflow-y-auto overscroll-contain">{cart.map((x,i)=><div key={x.id} className="grid grid-cols-[26px_minmax(0,1fr)_52px_64px_70px_24px] sm:grid-cols-[42px_minmax(180px,1fr)_78px_100px_110px_36px] items-center gap-1 sm:gap-2 border-b border-border px-2 py-2 text-xs last:border-b-0"><b className="text-center text-accent">{i+1}</b><div className="min-w-0"><b className="block truncate">{x.name}</b><span className="block truncate text-[10px] text-muted">{x.sku||x.barcode||''}</span>{x.serial_tracked&&<button type="button" onClick={()=>openSerials(x)} className="mt-1 text-[10px] font-black text-accent">السيريال ({x.serials.length}/{x.qty})</button>}</div><input ref={el=>{if(el)qtyRefs.current.set(String(x.id),el);else qtyRefs.current.delete(String(x.id))}} className="min-w-0 w-full rounded-lg border border-border bg-card px-0.5 py-2 text-center text-[11px] sm:px-1 sm:text-xs" type="number" min="1" value={x.qty} onChange={e=>setCart(v=>v.map(a=>a.id===x.id?{...a,qty:Number(e.target.value)}:a))}/><input className="min-w-0 w-full rounded-lg border border-border bg-card px-0.5 py-2 text-center text-[11px] sm:px-1 sm:text-xs" type="number" min="0" value={x.price} onChange={e=>setCart(v=>v.map(a=>a.id===x.id?{...a,price:e.target.value}:a))}/><b className="text-center" dir="ltr">{money(Number(x.qty||0)*Number(x.price||0))}</b><button type="button" onClick={()=>setCart(v=>v.filter(a=>a.id!==x.id))} className="text-lg font-black">×</button></div>)}{!cart.length&&<div className="grid min-h-[180px] place-items-center px-4 text-center text-xs text-muted">الأصناف المضافة ستظهر هنا: مسلسل، الصنف، الكمية، السعر، والإجمالي.</div>}</div><div className="flex items-center justify-between border-t border-border bg-card px-3 py-3 text-xs"><span>{itemCount} أصناف · {pieceCount} قطع</span><b className="text-base text-accent">{money(total)}</b></div></div></div>
  <button type="button" disabled={!cart.length} onClick={()=>goStage(3)} className="mt-4 w-full rounded-xl bg-accent px-4 py-3 font-black text-on-accent disabled:opacity-40">مراجعة الفاتورة ({pieceCount}) ←</button>
 </section>

 <section className={`${stage===3?'block':'hidden'} rounded-2xl border-2 border-accent-line bg-card p-4`}>
  <div className="mb-3 flex items-center justify-between"><div><h2 className="text-lg font-black text-accent">3. مراجعة الفاتورة</h2><p className="text-xs text-muted">راجع الأصناف والكميات والأسعار قبل الدفع.</p></div><b className="text-xl text-accent">{money(total)}</b></div>
  <div className="max-h-[52vh] overflow-y-auto rounded-2xl border border-border">{cart.map((x,i)=><div key={x.id} className="grid grid-cols-[34px_minmax(0,1fr)_auto] items-center gap-1 sm:gap-2 border-b border-border p-3 text-sm last:border-0"><b className="text-accent">{i+1}</b><div className="min-w-0"><b className="block truncate">{x.name}</b><span className="text-xs text-muted">{x.qty} × {money(x.price)}</span></div><b dir="ltr">{money(x.qty*Number(x.price||0))}</b></div>)}</div>
  <div className="mt-4 grid grid-cols-2 gap-2"><button type="button" onClick={()=>goStage(2)} className="rounded-xl border border-border px-4 py-3 font-black">تعديل الأصناف</button><button type="button" onClick={()=>goStage(4)} className="rounded-xl bg-accent px-4 py-3 font-black text-on-accent">متابعة للدفع ←</button></div>
 </section>

 <section className={`${stage===4?'block':'hidden'} rounded-2xl border-2 border-accent-line bg-card p-4`}>
  <div className="mb-4"><h2 className="text-lg font-black text-accent">4. الدفع وإتمام البيع</h2><p className="text-xs text-muted">حدد طريقة الدفع ثم أكد العملية.</p></div>
  <div className="grid gap-3 sm:grid-cols-2"><select className={I} value={paymentType} onChange={e=>{setPaymentType(e.target.value);setTreasury('')}}><option value="cash">نقدي</option><option value="credit">آجل</option></select>{paymentType==='cash'?<select className={I} value={treasury} onChange={e=>setTreasury(e.target.value)}><option value="">الخزينة المستلمة *</option>{treasuries.filter(t=>!t.branch||t.branch===branch).map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>:<div className="rounded-xl border border-border bg-surface px-3 py-2.5 text-sm">سيتم تسجيل المبلغ على حساب العميل.</div>}</div>
  <div className="mt-4 rounded-2xl border border-border bg-surface p-4"><div className="flex justify-between text-sm"><span>الأصناف</span><b>{itemCount}</b></div><div className="mt-2 flex justify-between text-sm"><span>القطع</span><b>{pieceCount}</b></div><div className="mt-4 flex items-end justify-between border-t border-border pt-4"><span className="font-black">الإجمالي النهائي</span><b className="text-3xl font-black text-accent">{money(total)}</b></div></div>
  <button disabled={busy} onClick={checkout} className="mt-4 w-full rounded-xl bg-accent px-5 py-4 text-lg font-black text-on-accent disabled:opacity-50">{busy?'جارٍ البيع…':'إتمام البيع'}</button>{msg&&<p className="mt-3 rounded-xl border border-accent-line bg-accent-soft p-3 text-xs font-bold text-accent">{msg}</p>}
 </section>

 {galleryOpen&&<div dir="rtl" className="fixed inset-0 z-[245] h-[100dvh] w-screen overflow-hidden bg-bg"><div className="flex h-full min-h-0 flex-col"><div className="shrink-0 border-b border-accent-line bg-card px-3 pb-3 pt-[max(.75rem,env(safe-area-inset-top))] shadow-lg"><div className="mx-auto flex max-w-6xl items-center justify-between gap-3"><div><h2 className="text-lg font-black text-accent">عرض الأصناف بالصور</h2><p className="text-xs text-muted">{shown.length} صنف · {branch}</p></div><button type="button" onClick={()=>setGalleryOpen(false)} className="rounded-xl border border-border px-4 py-2 font-black">← رجوع</button></div><div className="mx-auto mt-3 grid max-w-6xl grid-cols-2 gap-2"><div className="rounded-xl border border-accent-line bg-accent-soft p-3 text-center"><span className="block text-[11px] text-muted">إجمالي القطع المختارة</span><b className="text-xl text-accent">{pieceCount}</b></div><div className="rounded-xl border border-accent-line bg-accent-soft p-3 text-center"><span className="block text-[11px] text-muted">إجمالي الفاتورة الحالي</span><b className="text-xl text-accent" dir="ltr">{money(total)}</b></div></div><div className="mx-auto mt-2 grid max-w-6xl gap-2 sm:grid-cols-2"><SearchableFilter items={cats} value={cat} onChange={setCat} allLabel="كل الأقسام" placeholder="ابحث بجزء من اسم القسم"/><SearchableFilter items={brands} value={brand} onChange={setBrand} allLabel="كل العلامات التجارية" placeholder="ابحث بجزء من اسم العلامة"/></div></div><div className="min-h-0 flex-1 overflow-y-auto overscroll-contain pb-[max(1rem,env(safe-area-inset-bottom))]"><div className="mx-auto grid max-w-6xl grid-cols-2 gap-3 p-3 sm:grid-cols-3 md:grid-cols-4">{shown.map(p=><button key={p.id} onClick={()=>{if(add(p)){setQ('');setMsg(`تمت إضافة ${p.name} إلى الفاتورة ✓`);if(differentQty){setGalleryOpen(false);focusQty(p.id)}}}} className="overflow-hidden rounded-2xl border border-border bg-surface text-right active:scale-[.98]"><div className="aspect-square overflow-hidden bg-card">{p.images?.[0]?<img src={publicMediaUrl('product-images',p.images[0])} alt={p.name} loading="lazy" className="h-full w-full object-contain p-2"/>:<div className="grid h-full place-items-center text-4xl opacity-30">📦</div>}</div><div className="p-2"><b className="line-clamp-2 text-xs">{p.name}</b><div className="mt-1 text-[10px] text-muted">المخزون: {stockQty(movements,p.id,branch)}</div><div className="mt-1 flex items-center justify-between"><span className="text-xs font-black text-accent">{Number(p.sale_price||0).toLocaleString()}</span><span className="rounded-lg bg-accent px-2 py-1 font-black text-on-accent">+</span></div></div></button>)}</div></div></div></div>}
 {serialPicker&&<div className="fixed inset-0 z-[155] grid place-items-center bg-black/80 p-4"><div className="w-full max-w-lg rounded-3xl border border-accent-line bg-card p-5"><div className="flex justify-between"><div><h3 className="font-black text-accent">اختيار السيريال / IMEI</h3><p className="text-xs text-muted">{activeSerialProduct?.name}</p></div><button onClick={()=>setSerialPicker(null)}>✕</button></div><div className="mt-4 grid grid-cols-[minmax(0,1fr)_auto] gap-2"><input autoFocus dir="ltr" className={I} value={serialQuery} onChange={e=>setSerialQuery(e.target.value)} placeholder="اكتب جزءًا من السيريال أو استخدم القارئ" onKeyDown={e=>{if(e.key==='Enter'&&serialSuggestions.length===1){e.preventDefault();chooseSerial(serialSuggestions[0].serial_number)}}}/><button onClick={()=>setSerialScan(true)} className="rounded-xl border border-accent-line px-4 text-xl">📷</button></div><div className="mt-3 max-h-72 overflow-auto rounded-xl border border-border">{serialSuggestions.map(s=><button key={s.id} onClick={()=>chooseSerial(s.serial_number)} className="block w-full border-b border-border p-3 text-left font-bold last:border-0 hover:bg-surface" dir="ltr">{s.serial_number}</button>)}{serialQuery&&!serialSuggestions.length&&<div className="p-4 text-center text-sm text-muted">لا يوجد سيريال متاح مطابق في هذا الفرع.</div>}</div><button onClick={()=>setSerialPicker(null)} className="mt-4 w-full rounded-xl bg-accent px-4 py-3 font-black text-on-accent">تم</button></div></div>}
 {serialScan&&<BarcodeScanner label="السيريال / IMEI" onClose={()=>setSerialScan(false)} onDetected={code=>{setSerialScan(false);setSerialQuery(String(code));const s=serialRows.find(x=>String(x.serial_number)===String(code)&&!activeSerialProduct?.serials.includes(x.serial_number));if(s)chooseSerial(s.serial_number)}}/>}
 {success&&<div className="fixed inset-0 z-[150] grid place-items-center overflow-y-auto bg-black/80 p-4"><div className="w-full max-w-lg rounded-3xl border-2 border-accent-line bg-card p-6 shadow-2xl"><div className="text-center text-5xl">✓</div><h3 className="mt-2 text-center text-2xl font-black text-accent">تم البيع بنجاح</h3><div className="mt-5 grid grid-cols-2 gap-2 text-sm">{[['رقم الفاتورة',success.number],['الفرع',branch],['عدد الأصناف',success.items],['إجمالي عدد القطع',success.pieces],['العميل',success.customer],['رصيد العميل الحالي',customer?money(success.customerBalance):'—'],['حالة الدفع',success.payment],['رصيد الخزينة الآن',success.treasuryBalance===null?'—':money(success.treasuryBalance)]].map(([k,v])=><div key={k} className="rounded-xl border border-border p-3"><span className="block text-xs text-muted">{k}</span><b>{v}</b></div>)}</div><button disabled={!success.id} onClick={()=>setPrintId(success.id)} className="mt-5 w-full rounded-2xl bg-accent px-5 py-4 text-lg font-black text-on-accent disabled:opacity-40">🖨️ طباعة الفاتورة</button><button onClick={()=>setSuccess(null)} className="mt-2 w-full rounded-xl border border-border px-4 py-3 font-black">إغلاق</button></div></div>}
 {printId&&<InvoiceQuickView type="sales" invoiceId={printId} onClose={()=>setPrintId(null)}/>} {partyModal&&<div className="fixed inset-0 z-[140] overflow-y-auto bg-black/75 p-4"><div className="mx-auto my-8 max-w-4xl rounded-2xl border border-border bg-bg p-4"><button type="button" onClick={()=>setPartyModal('')} className="mb-3 text-xl">✕</button>{partyModal==='add'&&<div className="grid gap-3"><h3 className="font-black">إضافة عميل جديد</h3><input className={I} placeholder="اسم العميل *" value={newCustomer.display_name} onChange={e=>setNewCustomer({...newCustomer,display_name:e.target.value})}/><input className={I} placeholder="الهاتف" value={newCustomer.phone} onChange={e=>setNewCustomer({...newCustomer,phone:e.target.value})}/><button type="button" onClick={saveCustomer} className="rounded-xl bg-accent px-4 py-3 font-black text-on-accent">إضافة واختيار العميل</button></div>}{partyModal==='pay'&&<PartyPaymentsAdmin type="customer" initialPartyId={customer}/>} {partyModal==='statement'&&<PartyStatementAdmin type="customer" initialPartyId={customer}/>}</div></div>}</div></div>
}
