import { useEffect,useMemo,useState } from 'react';
import { supabase } from '../lib/supabase';
import ListPagination,{useListPagination} from './ui/ListPagination';
export default function ProductWarrantiesAdmin(){
 const [rows,setRows]=useState([]),[q,setQ]=useState(''),[onlyActive,setOnlyActive]=useState(false),[msg,setMsg]=useState('');
 const load=async()=>{const {data,error}=await supabase.from('product_warranties').select('*,products(id,sku,name),product_serials(serial_number)').order('created_at',{ascending:false}).limit(1000);setRows(data||[]);setMsg(error?.message||'')};useEffect(()=>{load()},[]);
 const today=new Date().toISOString().slice(0,10); const state=r=>!r.is_active?'موقوف':r.start_date&&r.start_date>today?'لم يبدأ':r.end_date&&r.end_date<today?'منتهي':'ساري';
 const shown=useMemo(()=>rows.filter(r=>(!onlyActive||state(r)==='ساري')&&((r.products?.name||'')+' '+(r.products?.sku||'')+' '+(r.product_serials?.serial_number||'')+' '+(r.reference_id||'')).toLowerCase().includes(q.toLowerCase())),[rows,q,onlyActive]);
 const pager=useListPagination(shown,[q,onlyActive]);
 const input='rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
 return <div><div className="mb-4 flex flex-wrap gap-3"><input className={`${input} min-w-0 flex-[1_1_260px]`} placeholder="بحث بالمنتج أو السريال أو المرجع" value={q} onChange={e=>setQ(e.target.value)}/><label className="flex items-center gap-2 rounded-xl border border-border bg-surface px-3 text-sm font-bold"><input type="checkbox" checked={onlyActive} onChange={e=>setOnlyActive(e.target.checked)}/> الضمانات السارية فقط</label></div>{msg&&<p className="mb-3 text-xs font-bold text-danger">{msg}</p>}<div className="overflow-x-auto rounded-2xl border border-border"><table className="w-full min-w-[920px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">المنتج</th><th className="p-3">السريال</th><th className="p-3">المدة</th><th className="p-3">البداية</th><th className="p-3">النهاية</th><th className="p-3">الحالة</th><th className="p-3">المرجع</th></tr></thead><tbody>{pager.visible.map(r=><tr key={r.id} className="border-t border-border"><td className="p-3"><b>{r.products?.name||'—'}</b><div className="text-xs text-muted">{r.products?.sku||''}</div></td><td className="p-3 font-bold text-accent">{r.product_serials?.serial_number||'—'}</td><td className="p-3">{r.warranty_days} يوم</td><td className="p-3">{r.start_date||'—'}</td><td className="p-3">{r.end_date||'—'}</td><td className="p-3 font-bold">{state(r)}</td><td className="p-3">{r.reference_type||'—'}{r.reference_id?` · ${r.reference_id}`:''}</td></tr>)}{!shown.length&&<tr><td colSpan="7" className="p-8 text-center text-muted">لا توجد ضمانات مطابقة.</td></tr>}</tbody></table></div><ListPagination {...pager}/><p className="mt-3 text-xs leading-6 text-muted">الضمان مرتبط بالمنتج والسريال، ويبدأ من مستند البيع عند تفعيل دورة المبيعات. هذه الشاشة مخصصة للتتبع والمراجعة.</p></div>
}