import { useEffect, useMemo, useRef, useState } from 'react';
import { supabase } from '../lib/supabase';
import Button from './ui/Button';
import { useAllowedBranches } from '../hooks/useAllowedBranches';
import { usePermissions } from '../context/PermissionContext';
import ListPagination,{useListPagination} from './ui/ListPagination';
import BarcodeScanner from './BarcodeScanner';
import PartySmartSearch from './ui/PartySmartSearch';
import PartyPaymentsAdmin from './PartyPaymentsAdmin';
import PartyStatementAdmin from './PartyStatementAdmin';
import InvoiceQuickView from './InvoiceQuickView';
import ERPDocumentViewer from './ERPDocumentViewer';
import PartyAccountSummary from './ui/PartyAccountSummary';

const input='w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
const newItem=()=>({product_id:'',quantity:'1',unit_cost:'0',serials:''});
const blankProduct={sku:'',barcode:'',name:'',unit_id:'',category_id:'',brand_id:'',purchase_price:'0',sale_price:'0',serial_tracked:false,warranty_days:0,is_active:true,notes:'',images:[]};
const today=()=>new Date().toISOString().slice(0,10);
const number=()=>`PI-${Date.now()}`;
const norm=v=>String(v??'').trim().toLowerCase();

export default function PurchaseInvoicesAdmin({mode='list'}){
 const {branches,canAccessBranch}=useAllowedBranches();
 const {can}=usePermissions();
 const [rows,setRows]=useState([]),[suppliers,setSuppliers]=useState([]),[products,setProducts]=useState([]),[treasuries,setTreasuries]=useState([]),[items,setItems]=useState([newItem()]);
 const [units,setUnits]=useState([]),[cats,setCats]=useState([]),[brands,setBrands]=useState([]);
 const [form,setForm]=useState({invoice_number:number(),supplier_invoice_number:'',supplier_id:'',branch:'',invoice_date:today(),discount:'0',payment_type:'cash',treasury_id:'',notes:''});
 const [busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const [search,setSearch]=useState(''),[suggestOpen,setSuggestOpen]=useState(false),[differentQty,setDifferentQty]=useState(false),[scanner,setScanner]=useState(false);
 const [missingOpen,setMissingOpen]=useState(false),[productOpen,setProductOpen]=useState(false),[newProduct,setNewProduct]=useState(blankProduct),[productBusy,setProductBusy]=useState(false);
 const [partyModal,setPartyModal]=useState(''),[newSupplier,setNewSupplier]=useState({name:'',phone:''}),[viewInvoiceId,setViewInvoiceId]=useState(null),[successInvoiceId,setSuccessInvoiceId]=useState(null),[successNumber,setSuccessNumber]=useState(''),[editing,setEditing]=useState(null);
 const searchRef=useRef(null),qtyRefs=useRef({});

 const load=async()=>{const [a,b,c,d,u,ca,br]=await Promise.all([
  supabase.from('purchase_invoices').select('*, suppliers(name), purchase_invoice_items(*, products(name,sku,serial_tracked))').order('created_at',{ascending:false}),
  supabase.from('suppliers').select('id,name,code').eq('is_active',true).order('name'),
  supabase.from('products').select('id,name,sku,barcode,serial_tracked,purchase_price,sale_price,unit_id,category_id,brand_id').eq('is_active',true).order('name'),
  supabase.from('treasuries').select('id,name,branch').eq('is_active',true).order('name'),
  supabase.from('product_units').select('id,name').order('name'),supabase.from('product_categories').select('id,name').order('name'),supabase.from('product_brands').select('id,name').order('name')
 ]);for(const x of [a,b,c,d,u,ca,br])if(x.error)throw x.error;setRows((a.data||[]).filter(x=>canAccessBranch(x.branch)));setSuppliers(b.data||[]);setProducts(c.data||[]);setTreasuries(d.data||[]);setUnits(u.data||[]);setCats(ca.data||[]);setBrands(br.data||[])};
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[branches]);

 const suggestions=useMemo(()=>{const q=norm(search);if(!q)return[];return products.filter(p=>norm(`${p.name} ${p.sku} ${p.barcode||''}`).includes(q)).slice(0,8)},[products,search]);
 const subtotal=useMemo(()=>items.reduce((s,x)=>s+(Number(x.quantity)||0)*(Number(x.unit_cost)||0),0),[items]); const total=Math.max(0,subtotal-(Number(form.discount)||0));
 const setItem=(i,k,v)=>setItems(xs=>xs.map((x,n)=>n===i?{...x,[k]:v}:x));

 const chooseProduct=async product=>{
   const cost=Number(product.purchase_price||0);
   setItems(xs=>{
     const empty=xs.findIndex(x=>!x.product_id);
     const line={product_id:String(product.id),quantity:'1',unit_cost:String(cost),serials:''};
     return empty>=0?xs.map((x,i)=>i===empty?line:x):[...xs,line];
   });
   setSearch('');setSuggestOpen(false);
   setTimeout(()=>{if(differentQty){const index=(items.findIndex(x=>!x.product_id)>=0?items.findIndex(x=>!x.product_id):items.length);qtyRefs.current[index]?.focus();qtyRefs.current[index]?.select()}else searchRef.current?.focus()},50);
 };
 const submitSearch=()=>{
   const q=norm(search);if(!q)return;
   const exact=products.find(p=>[p.barcode,p.sku,p.name].some(v=>norm(v)===q));
   if(exact)return chooseProduct(exact);
   if(suggestions.length===1)return chooseProduct(suggestions[0]);
   if(suggestions.length){setSuggestOpen(true);return}
   setMissingOpen(true);
 };
 const scanDetected=code=>{setScanner(false);setSearch(code);const p=products.find(x=>norm(x.barcode)===norm(code)||norm(x.sku)===norm(code));if(p)chooseProduct(p);else setMissingOpen(true)};

 const openNewProduct=()=>{setMissingOpen(false);setNewProduct({...blankProduct,name:search});setProductOpen(true)};
 const saveNewProduct=async e=>{
   e.preventDefault();if(!newProduct.name.trim())return setMsg('اسم الصنف مطلوب.');
   setProductBusy(true);setMsg('');
   try{
     const payload={...newProduct,unit_id:newProduct.unit_id||null,category_id:newProduct.category_id||null,brand_id:newProduct.brand_id||null,sku:(newProduct.sku||'').trim()||null,barcode:(newProduct.barcode||'').trim()||null,purchase_price:Number(newProduct.purchase_price||0),sale_price:Number(newProduct.sale_price||0),warranty_days:Number(newProduct.warranty_days||0)};
     const {data,error}=await supabase.from('products').insert(payload).select('id,name,sku,barcode,serial_tracked,purchase_price,sale_price,unit_id,category_id,brand_id').single();if(error)throw error;
     setProducts(v=>[...v,data].sort((a,b)=>a.name.localeCompare(b.name)));setProductOpen(false);setSearch('');await chooseProduct(data);setMsg('تم إنشاء الصنف وإضافته إلى فاتورة الشراء.');
   }catch(e){setMsg(e.message)}finally{setProductBusy(false)}
 };

 const validate=async()=>{if(!form.supplier_id)return 'اختر المورد.';if(!form.branch)return 'حدد الفرع / المخزن المستلم.';if(!canAccessBranch(form.branch))return 'ليس لديك صلاحية على هذا الفرع.';if(!form.payment_type)return 'حدد طريقة الدفع.';if(form.payment_type==='cash'&&!form.treasury_id)return 'حدد الخزينة المدفوع منها.';const valid=items.filter(x=>x.product_id);if(!valid.length)return 'أضف صنفًا واحدًا على الأقل.';const all=[];for(const x of valid){const p=products.find(y=>String(y.id)===String(x.product_id)),q=Number(x.quantity);if(!p||q<=0)return 'راجع الصنف والكمية.';if(p.serial_tracked){if(!Number.isInteger(q))return `كمية ${p.name} يجب أن تكون عددًا صحيحًا.`;const ss=x.serials.split(/[,\n]+/).map(s=>s.trim()).filter(Boolean);if(ss.length!==q)return `${p.name}: عدد السريلات يجب أن يساوي الكمية (${q}).`;all.push(...ss)}}if(new Set(all).size!==all.length)return 'يوجد سيريال مكرر داخل الفاتورة.';if(all.length){const {data,error}=await supabase.from('product_serials').select('serial_number,status,product_id').in('serial_number',all);if(error)return error.message;const blocked=(data||[]).find(s=>s.status!=='returned'||!valid.some(x=>Number(x.product_id)===Number(s.product_id)&&x.serials.split(/[,\n]+/).map(v=>v.trim()).includes(s.serial_number)));if(blocked)return `السيريال ${blocked.serial_number} مسجل مسبقًا وغير متاح لإعادة الشراء.`}return ''};
 const save=async(post=false)=>{setBusy(true);setMsg('');try{const problem=await validate();if(problem)throw new Error(problem);const valid=items.filter(x=>x.product_id);const lines=valid.map(x=>{const product=products.find(p=>String(p.id)===String(x.product_id));return {product_id:Number(x.product_id),quantity:Number(x.quantity),unit_cost:Number(x.unit_cost)||0,serial_numbers:product?.serial_tracked?x.serials.split(/[,\n]+/).map(s=>s.trim()).filter(Boolean):[]};});if(editing){const header={...form,supplier_id:Number(form.supplier_id),treasury_id:form.payment_type==='cash'?Number(form.treasury_id):null,subtotal,discount:Number(form.discount)||0,total};if(editing.status==='posted'){const{error}=await supabase.rpc('edit_posted_purchase_invoice_tx',{p_invoice_id:editing.id,p_header:header,p_items:lines});if(error)throw error;setMsg('تم تعديل الفاتورة المرحلة وتحديث أثرها المخزني والمحاسبي بنجاح.');}else{const draftHeader={...header,paid:0,status:'draft',posted_at:null};const{error}=await supabase.from('purchase_invoices').update(draftHeader).eq('id',editing.id);if(error)throw error;const{error:de}=await supabase.from('purchase_invoice_items').delete().eq('invoice_id',editing.id);if(de)throw de;const{error:ie}=await supabase.from('purchase_invoice_items').insert(lines.map(x=>({...x,invoice_id:editing.id})));if(ie)throw ie;setMsg('تم حفظ تعديلات فاتورة الشراء.');}setEditing(null);}else if(post){const header={...form,supplier_id:Number(form.supplier_id),subtotal,discount:Number(form.discount)||0,total};const{data,error}=await supabase.rpc('post_purchase_invoice_tx',{p_header:header,p_items:lines});if(error)throw error;const savedNumber=data?.number||data?.invoice_number||form.invoice_number;let savedId=data?.id||data?.invoice_id||null;if(!savedId){const found=await supabase.from('purchase_invoices').select('id').eq('invoice_number',savedNumber).maybeSingle();savedId=found.data?.id||null}setSuccessNumber(savedNumber);setSuccessInvoiceId(savedId);setMsg('')}else if(!editing){const header={...form,supplier_id:Number(form.supplier_id),treasury_id:form.payment_type==='cash'?Number(form.treasury_id):null,subtotal,discount:Number(form.discount)||0,total,paid:0,status:'draft',posted_at:null};const{data:inv,error}=await supabase.from('purchase_invoices').insert(header).select().single();if(error)throw error;const{error:ie}=await supabase.from('purchase_invoice_items').insert(lines.map(x=>({...x,invoice_id:inv.id})));if(ie)throw ie;setMsg('تم حفظ فاتورة الشراء كمسودة.')}setForm({invoice_number:number(),supplier_invoice_number:'',supplier_id:'',branch:'',invoice_date:today(),discount:'0',payment_type:'cash',treasury_id:'',notes:''});setItems([newItem()]);await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}};

 const startEdit=r=>{if(r.status==='cancelled')return setMsg('لا يمكن تعديل فاتورة ملغاة.');setEditing(r);setForm({invoice_number:r.invoice_number||number(),supplier_invoice_number:r.supplier_invoice_number||'',supplier_id:String(r.supplier_id||''),branch:r.branch||'',invoice_date:r.invoice_date||today(),discount:String(r.discount||0),payment_type:r.payment_type||'cash',treasury_id:r.treasury_id?String(r.treasury_id):'',notes:r.notes||''});setItems((r.purchase_invoice_items||[]).map(x=>({product_id:String(x.product_id),quantity:String(x.quantity),unit_cost:String(x.unit_cost||0),serials:(x.serial_numbers||[]).join('\n')})));window.scrollTo({top:0,behavior:'smooth'});};
 const deleteInvoice=async r=>{if(r.status!=='draft')return setMsg('لا يتم حذف فاتورة شراء مرحلة لأنها أثرت على المخزون والحسابات. استخدم إلغاء/عكس المستند من حماية المستندات.');if(!confirm(`حذف مسودة فاتورة الشراء ${r.invoice_number} نهائيًا؟`))return;setBusy(true);setMsg('');try{const{error:ie}=await supabase.from('purchase_invoice_items').delete().eq('invoice_id',r.id);if(ie)throw ie;const{error}=await supabase.from('purchase_invoices').delete().eq('id',r.id);if(error)throw error;if(editing?.id===r.id)setEditing(null);setMsg('تم حذف مسودة فاتورة الشراء.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const cancelInvoice=async r=>{if(r.status==='cancelled')return;if(r.status!=='posted')return setMsg('يتم إلغاء الفواتير المرحلة فقط.');if(!can('can_erp_cancel'))return setMsg('لا توجد صلاحية إلغاء/عكس فاتورة الشراء.');const reason=window.prompt('سبب إلغاء فاتورة الشراء:');if(!reason?.trim())return;setBusy(true);setMsg('');try{const{error}=await supabase.rpc('cancel_purchase_invoice_tx',{p_invoice_id:r.id,p_reason:reason.trim()});if(error)throw error;setViewInvoiceId(null);setMsg('تم إلغاء/عكس فاتورة الشراء.');await load()}catch(e){setMsg(e.message)}finally{setBusy(false)}};

 const saveSupplier=async()=>{if(!newSupplier.name.trim())return setMsg('اسم المورد مطلوب.');const code=String(Math.max(999,...suppliers.map(x=>Number(x.code)||0))+1);const {data,error}=await supabase.from('suppliers').insert({name:newSupplier.name.trim(),phone:newSupplier.phone.trim()||null,code,is_active:true,opening_balance:0}).select('id,name,code,phone').single();if(error)return setMsg(error.message);setSuppliers(v=>[...v,data].sort((a,b)=>a.name.localeCompare(b.name)));setForm(f=>({...f,supplier_id:String(data.id)}));setNewSupplier({name:'',phone:''});setPartyModal('');};
 const pager=useListPagination(rows);
 return <div className="space-y-4">{(mode==='create'||editing)&&<section className="mx-auto w-full max-w-5xl rounded-2xl border border-border bg-card p-4">
  <div className="mb-4 flex items-start justify-between gap-3"><div><h3 className="font-black text-text">{editing?'تعديل فاتورة شراء':'فاتورة شراء جديدة'}</h3>{editing&&<p className="mt-1 text-xs text-muted">تعديل المسودة {editing.invoice_number}</p>}</div>{editing&&<button type="button" onClick={()=>setEditing(null)} className="rounded-xl border border-border px-3 py-2 text-xs font-black">إلغاء التعديل</button>}</div><p className="text-xs text-muted">إدخال سريع بالاسم أو جزء منه أو SKU أو الباركود، مع اقتراحات فورية.</p>
  <div className="grid gap-3 md:grid-cols-3"><input className={input} value={form.invoice_number} onChange={e=>setForm({...form,invoice_number:e.target.value})} placeholder="رقم الفاتورة"/><div className="md:col-span-2"><div className="grid gap-2 sm:grid-cols-[minmax(0,1fr)_auto_auto_auto]"><PartySmartSearch parties={suppliers} type="supplier" value={form.supplier_id} onSelect={p=>setForm({...form,supplier_id:p?String(p.id):''})} placeholder="اكتب جزءًا من اسم المورد *"/><button type="button" onClick={()=>setPartyModal('add')} className="rounded-xl border border-border px-3 font-black">+ مورد</button><button type="button" disabled={!form.supplier_id} onClick={()=>setPartyModal('pay')} className="rounded-xl border border-border px-3 text-xs font-black disabled:opacity-40">سداد دفعة</button><button type="button" disabled={!form.supplier_id} onClick={()=>setPartyModal('statement')} className="rounded-xl border border-border px-3 text-xs font-black disabled:opacity-40">كشف حساب</button></div>{form.supplier_id&&<div className="mt-2"><PartyAccountSummary type="supplier" partyId={form.supplier_id}/></div>}</div><input className={input} value={form.supplier_invoice_number} onChange={e=>setForm({...form,supplier_invoice_number:e.target.value})} placeholder="رقم فاتورة المورد"/><select className={input} value={form.branch} onChange={e=>setForm({...form,branch:e.target.value,treasury_id:''})}><option value="">اختر الفرع *</option>{branches.map(b=><option key={b} value={b}>{b}</option>)}</select><input className={input} type="date" value={form.invoice_date} onChange={e=>setForm({...form,invoice_date:e.target.value})}/><select className={input} value={form.payment_type} onChange={e=>setForm({...form,payment_type:e.target.value,treasury_id:''})}><option value="cash">نقدي</option><option value="credit">آجل</option></select>{form.payment_type==='cash'&&<select className={input} value={form.treasury_id} onChange={e=>setForm({...form,treasury_id:e.target.value})}><option value="">الخزينة المدفوع منها *</option>{treasuries.filter(t=>!t.branch||t.branch===form.branch).map(t=><option key={t.id} value={t.id}>{t.name}{t.branch?` — ${t.branch}`:''}</option>)}</select>}<input className={input} value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})} placeholder="ملاحظات"/></div>

  <div className="mt-5 rounded-2xl border border-border bg-surface/40 p-3">
   <div className="mb-2 flex flex-wrap items-center justify-between gap-2"><b>إضافة أصناف الفاتورة</b><label className="flex cursor-pointer items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-black"><input type="checkbox" checked={differentQty} onChange={e=>setDifferentQty(e.target.checked)}/> كميات مختلفة</label></div>
   <div className="relative grid gap-2 sm:grid-cols-[1fr_auto_auto]">
    <div className="relative"><input ref={searchRef} autoFocus className={input} value={search} onChange={e=>{setSearch(e.target.value);setSuggestOpen(true)}} onFocus={()=>search&&setSuggestOpen(true)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();submitSearch()}}} placeholder="اكتب اسم الصنف أو جزء منه / SKU / امسح الباركود" autoComplete="off"/>
     {suggestOpen&&search&&suggestions.length>0&&<div className="absolute inset-x-0 top-full z-40 mt-1 max-h-72 overflow-auto rounded-xl border border-border bg-bg shadow-2xl">{suggestions.map(p=><button type="button" key={p.id} onClick={()=>chooseProduct(p)} className="block w-full border-b border-border p-3 text-right last:border-0 hover:bg-surface"><b className="block">{p.name}</b><span className="text-xs text-muted">{p.sku}{p.barcode?` · ${p.barcode}`:''} · آخر شراء {Number(p.purchase_price||0).toLocaleString()}</span></button>)}</div>}
    </div>
    <button type="button" onClick={submitSearch} className="rounded-xl border border-accent-line px-4 py-2 text-xs font-black text-accent">بحث / Enter</button>
    <button type="button" onClick={()=>setScanner(true)} className="rounded-xl border border-accent-line px-4 py-2 text-xs font-black text-accent">📷 باركود</button>
   </div>
   <button type="button" onClick={()=>{setSearch('');setNewProduct(blankProduct);setProductOpen(true)}} className="mt-3 rounded-xl bg-accent px-4 py-2 text-xs font-black text-black">+ إضافة صنف جديد مباشرة</button>
  </div>

  <div className="mt-4 rounded-2xl border-2 border-accent-line bg-surface/40 p-3"><div className="mb-3 border-b border-border pb-3"><h4 className="font-black text-accent">أصناف الفاتورة المضافة</h4><p className="text-xs text-muted">راجع الأصناف والكميات والأسعار والسيريالات قبل الحفظ.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-2">الصنف</th><th className="p-2">الكمية</th><th className="p-2">سعر الشراء</th><th className="p-2">السريلات</th><th className="p-2">الإجمالي</th><th></th></tr></thead><tbody>{items.filter(x=>x.product_id).map((x,i)=>{const p=products.find(y=>String(y.id)===String(x.product_id));return <tr key={`${x.product_id}-${i}`} className="border-t border-border"><td className="p-2"><b>{p?.name}</b><div className="text-xs text-muted">{p?.sku}{p?.barcode?` · ${p.barcode}`:''}</div></td><td className="p-2"><input ref={el=>qtyRefs.current[i]=el} className={input} type="number" min="0.001" step={p?.serial_tracked?'1':'0.001'} value={x.quantity} onChange={e=>setItem(items.findIndex(v=>v===x),'quantity',e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();searchRef.current?.focus()}}}/></td><td className="p-2"><input className={input} type="number" min="0" step="0.01" value={x.unit_cost} onChange={e=>setItem(items.findIndex(v=>v===x),'unit_cost',e.target.value)}/></td><td className="p-2"><textarea className={`${input} min-h-10`} disabled={!p?.serial_tracked} value={x.serials} onChange={e=>setItem(items.findIndex(v=>v===x),'serials',e.target.value)} placeholder={p?.serial_tracked?'سيريال لكل سطر':'غير متتبع'}/></td><td className="p-2 font-bold text-text">{((Number(x.quantity)||0)*(Number(x.unit_cost)||0)).toLocaleString()}</td><td className="p-2"><button type="button" onClick={()=>setItems(v=>v.filter(y=>y!==x))} className="text-xs font-bold text-muted">حذف</button></td></tr>})}</tbody></table>{!items.some(x=>x.product_id)&&<div className="p-5 text-center text-xs text-muted">ابدأ بكتابة اسم الصنف أو امسح الباركود.</div>}</div></div>

  <div className="mt-4 rounded-2xl border-2 border-accent-line bg-accent-soft/30 p-4"><h4 className="mb-3 font-black text-accent">البيانات الحسابية</h4><div className="grid gap-3 md:grid-cols-4"><div><div className="text-xs text-muted">الإجمالي قبل الخصم</div><div className="font-black text-text">{subtotal.toLocaleString()}</div></div><input className={input} type="number" min="0" step="0.01" value={form.discount} onChange={e=>setForm({...form,discount:e.target.value})} placeholder="الخصم"/><div className="rounded-xl border border-border bg-surface px-3 py-2 text-sm">{form.payment_type==='cash'?'سيتم سداد كامل الفاتورة من الخزينة':'سيتم تسجيل كامل الفاتورة كمستحق للمورد'}</div><div><div className="text-xs text-muted">صافي الفاتورة / المتبقي</div><div className="font-black text-accent">{total.toLocaleString()} / {form.payment_type==='credit'?total.toLocaleString():'0'}</div></div></div><div className="mt-4 flex flex-wrap gap-2"><Button disabled={busy} onClick={()=>save(false)}>{editing?'حفظ التعديلات':'حفظ مسودة'}</Button>{!editing&&<Button disabled={busy} onClick={()=>save(true)}>حفظ وترحيل للمخزون</Button>}</div>{msg&&<p className="mt-3 text-sm font-bold text-accent">{msg}</p>}</div>
 </section>}

 {successNumber&&<div className="fixed inset-0 z-[150] grid place-items-center bg-black/80 p-4"><div className="w-full max-w-md rounded-3xl border-2 border-accent-line bg-card p-6 text-center shadow-2xl"><div className="text-5xl">✓</div><h3 className="mt-3 text-xl font-black text-accent">تم حفظ الفاتورة بنجاح</h3><p className="mt-2 text-sm text-muted">فاتورة الشراء <b className="text-text">{successNumber}</b> تم حفظها وترحيلها.</p><div className="mt-5 grid grid-cols-2 gap-2"><button type="button" disabled={!successInvoiceId} onClick={()=>setViewInvoiceId(successInvoiceId)} className="rounded-xl bg-accent px-4 py-3 font-black text-on-accent disabled:opacity-40">🖨️ طباعة</button><button type="button" onClick={()=>{setSuccessNumber('');setSuccessInvoiceId(null)}} className="rounded-xl border border-border px-4 py-3 font-black">إغلاق</button></div></div></div>}
 {viewInvoiceId&&<ERPDocumentViewer type="purchase_invoice" id={viewInvoiceId} onClose={()=>setViewInvoiceId(null)}/>} 
 {mode==='list'&&<section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-4"><h3 className="font-black text-text">فواتير المشتريات</h3><p className="text-xs text-muted">{rows.length} فاتورة</p></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">الفاتورة</th><th className="p-3">المورد</th><th className="p-3">الفرع</th><th className="p-3">التاريخ</th><th className="p-3">الإجمالي</th><th className="p-3">الحالة</th><th className="p-3">إجراءات</th></tr></thead><tbody>{pager.visible.map(r=><tr key={r.id} className="border-t border-border"><td className="p-3"><button type="button" onClick={()=>setViewInvoiceId(r.id)} className="font-bold text-accent underline decoration-accent/40 underline-offset-4">{r.invoice_number}</button></td><td className="p-3 text-text">{r.suppliers?.name||'—'}</td><td className="p-3 text-muted">{r.branch||'—'}</td><td className="p-3 text-muted">{r.invoice_date}</td><td className="p-3 font-bold text-text">{Number(r.total||0).toLocaleString()}</td><td className="p-3"><span className="rounded-full bg-accent-soft px-2 py-1 text-xs font-bold text-accent">{r.status==='posted'?'مرحلة':r.status==='draft'?'مسودة':'ملغاة'}</span></td><td className="p-3"><div className="flex flex-wrap gap-2"><button type="button" onClick={()=>startEdit(r)} disabled={r.status==='cancelled'} className="rounded-lg border border-border px-2 py-1 text-xs font-black disabled:opacity-35">تعديل</button><button type="button" onClick={()=>deleteInvoice(r)} disabled={busy||r.status!=='draft'} className="rounded-lg border border-danger/40 px-2 py-1 text-xs font-black text-danger disabled:opacity-35">حذف</button>{r.status==='posted'&&<button type="button" onClick={()=>cancelInvoice(r)} disabled={busy} className="rounded-lg border border-danger/40 px-2 py-1 text-xs font-black text-danger disabled:opacity-35">إلغاء/عكس</button>}</div></td></tr>)}{!rows.length&&<tr><td colSpan="7" className="p-8 text-center text-muted">لا توجد فواتير مشتريات بعد.</td></tr>}</tbody></table></div><ListPagination {...pager}/></section>}

 {partyModal&&<div className="fixed inset-0 z-[125] overflow-y-auto bg-black/75 p-4"><div className="mx-auto my-8 max-w-4xl rounded-2xl border border-border bg-bg p-4"><button type="button" onClick={()=>setPartyModal('')} className="mb-3 text-xl">✕</button>{partyModal==='add'&&<div className="grid gap-3"><h3 className="font-black">إضافة مورد جديد</h3><input className={input} placeholder="اسم المورد *" value={newSupplier.name} onChange={e=>setNewSupplier({...newSupplier,name:e.target.value})}/><input className={input} placeholder="الهاتف" value={newSupplier.phone} onChange={e=>setNewSupplier({...newSupplier,phone:e.target.value})}/><button type="button" onClick={saveSupplier} className="rounded-xl bg-accent px-4 py-3 font-black text-on-accent">إضافة واختيار المورد</button></div>}{partyModal==='pay'&&<PartyPaymentsAdmin type="supplier" initialPartyId={form.supplier_id}/>} {partyModal==='statement'&&<PartyStatementAdmin type="supplier" initialPartyId={form.supplier_id}/>}</div></div>}
 {scanner&&<BarcodeScanner label="باركود / SKU الصنف" onClose={()=>setScanner(false)} onDetected={scanDetected}/>}
 {missingOpen&&<div className="fixed inset-0 z-[110] grid place-items-center bg-black/70 p-4"><div className="relative w-full max-w-md rounded-2xl border border-border bg-bg p-5"><button type="button" onClick={()=>setMissingOpen(false)} className="absolute left-4 top-3 text-2xl text-muted">×</button><h3 className="text-lg font-black">هذا الصنف غير موجود</h3><p className="mt-2 text-sm text-muted">لم نجد صنفًا مطابقًا لـ <b className="text-text">{search}</b>. هل تريد إضافة صنف جديد؟</p><div className="mt-5 flex gap-2"><Button type="button" onClick={openNewProduct}>إضافة</Button><button type="button" onClick={()=>setMissingOpen(false)} className="rounded-xl border border-border px-4 py-2 text-sm font-bold">إلغاء</button></div></div></div>}
 {productOpen&&<div className="fixed inset-0 z-[120] grid place-items-center bg-black/75 p-4"><form onSubmit={saveNewProduct} className="relative max-h-[92vh] w-full max-w-2xl overflow-auto rounded-2xl border border-border bg-bg p-5"><button type="button" onClick={()=>setProductOpen(false)} className="absolute left-4 top-3 text-2xl text-muted">×</button><h3 className="mb-4 text-lg font-black">إضافة صنف جديد</h3><div className="grid gap-3 sm:grid-cols-2"><input className={`${input} sm:col-span-2`} placeholder="SKU / كود المصنع (باركود) — سيبها فاضية للتوليد التلقائي" value={newProduct.sku} onChange={e=>setNewProduct({...newProduct,sku:e.target.value})} autoComplete="off"/><input className={`${input} sm:col-span-2`} placeholder="اسم الصنف *" value={newProduct.name} onChange={e=>setNewProduct({...newProduct,name:e.target.value})}/><select className={input} value={newProduct.unit_id} onChange={e=>setNewProduct({...newProduct,unit_id:e.target.value})}><option value="">الوحدة</option>{units.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={input} value={newProduct.category_id} onChange={e=>setNewProduct({...newProduct,category_id:e.target.value})}><option value="">القسم</option>{cats.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><select className={input} value={newProduct.brand_id} onChange={e=>setNewProduct({...newProduct,brand_id:e.target.value})}><option value="">العلامة التجارية</option>{brands.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select><input className={input} type="number" min="0" step="0.01" placeholder="سعر الشراء *" value={newProduct.purchase_price} onChange={e=>setNewProduct({...newProduct,purchase_price:e.target.value})}/><input className={input} type="number" min="0" step="0.01" placeholder="Base Price *" value={newProduct.sale_price} onChange={e=>setNewProduct({...newProduct,sale_price:e.target.value})}/><input className={input} type="number" min="0" placeholder="مدة الضمان باليوم" value={newProduct.warranty_days} onChange={e=>setNewProduct({...newProduct,warranty_days:e.target.value})}/><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={newProduct.serial_tracked} onChange={e=>setNewProduct({...newProduct,serial_tracked:e.target.checked})}/> يتتبع بالسريال</label><textarea className={`${input} sm:col-span-2`} placeholder="ملاحظات" value={newProduct.notes} onChange={e=>setNewProduct({...newProduct,notes:e.target.value})}/></div><div className="mt-4 flex gap-2"><Button type="submit" disabled={productBusy}>{productBusy?'جارٍ الإضافة…':'إضافة الصنف للفاتورة'}</Button><button type="button" onClick={()=>setProductOpen(false)} className="rounded-xl border border-border px-4 py-2 text-sm font-bold">إلغاء</button></div></form></div>}
 </div>
}
