import { useEffect,useMemo,useState } from 'react';
import * as XLSX from 'xlsx';
import { supabase } from '../lib/supabase';
import { usePermissions } from '../context/PermissionContext';
import ListPagination,{useListPagination} from './ui/ListPagination';

const blank={name:'',app_code:'',description:'',is_active:true};
const input='w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
export default function SalePriceGroupsAdmin(){
 const {can}=usePermissions(); const [rows,setRows]=useState([]),[form,setForm]=useState(blank),[edit,setEdit]=useState(null),[q,setQ]=useState(''),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false);
 const load=async()=>{const{data,error}=await supabase.from('sale_price_groups').select('*').order('name');if(error)setMsg(error.message);else setRows(data||[])}; useEffect(()=>{load()},[]);
 const shown=useMemo(()=>rows.filter(x=>(x.name+' '+x.app_code+' '+(x.description||'')).toLowerCase().includes(q.toLowerCase())),[rows,q]);
  const pager=useListPagination(shown,[q]);
 const save=async e=>{e.preventDefault();if(!form.name.trim()||!form.app_code.trim())return setMsg('الاسم وكود التطبيق مطلوبان.');const perm=edit?'can_erp_price_group_edit':'can_erp_price_group_create';if(!can(perm))return setMsg('ليس لديك صلاحية تنفيذ هذه العملية.');setBusy(true);const payload={name:form.name.trim(),app_code:form.app_code.trim(),description:form.description.trim()||null};const{error}=edit?await supabase.from('sale_price_groups').update(payload).eq('id',edit):await supabase.from('sale_price_groups').insert(payload);setBusy(false);setMsg(error?error.message:(edit?'تم تعديل مجموعة الأسعار.':'تم إنشاء مجموعة الأسعار.'));if(!error){setForm(blank);setEdit(null);load()}};
 const toggle=async r=>{if(!can('can_erp_price_group_toggle'))return setMsg('ليس لديك صلاحية إيقاف/تفعيل مجموعات الأسعار.');const{error}=await supabase.from('sale_price_groups').update({is_active:!r.is_active}).eq('id',r.id);setMsg(error?error.message:(r.is_active?'تم إيقاف المجموعة ولن تظهر في المنتجات.':'تم تفعيل المجموعة.'));if(!error)load()};
 const downloadTemplate=()=>{const ws=XLSX.utils.aoa_to_sheet([['الاسم *','كود التطبيق *','الوصف'],['قطاعي','RETAIL','سعر البيع للقطاعي']]);ws['!cols']=[{wch:24},{wch:22},{wch:42}];const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'مجموعات الأسعار');XLSX.writeFile(wb,'APPTECH_Sale_Price_Groups_Template.xlsx')};
 const exportRows=()=>{if(!can('can_erp_price_group_export'))return setMsg('ليس لديك صلاحية التصدير.');const ws=XLSX.utils.json_to_sheet(rows.map(r=>({'الاسم':r.name,'كود التطبيق':r.app_code,'الوصف':r.description||'','الحالة':r.is_active?'نشط':'موقوف'})));const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,'مجموعات الأسعار');XLSX.writeFile(wb,'APPTECH_Sale_Price_Groups.xlsx')};
 const importFile=async e=>{const file=e.target.files?.[0];if(!file)return;if(!can('can_erp_price_group_import')){setMsg('ليس لديك صلاحية الاستيراد.');e.target.value='';return}try{const wb=XLSX.read(await file.arrayBuffer());const raw=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});const val=(r,keys)=>{for(const k of keys)if(r[k]!==undefined)return String(r[k]).trim();return''};const payload=raw.map(r=>({name:val(r,['الاسم','الاسم *','name']),app_code:val(r,['كود التطبيق','كود التطبيق *','app_code','code']),description:val(r,['الوصف','description'])||null})).filter(x=>x.name&&x.app_code);if(!payload.length)throw Error('لا توجد صفوف صالحة.');const{error}=await supabase.from('sale_price_groups').upsert(payload,{onConflict:'app_code',ignoreDuplicates:false});if(error)throw error;setMsg(`تم استيراد/تحديث ${payload.length} مجموعة أسعار.`);load()}catch(err){setMsg('فشل الاستيراد: '+err.message)}finally{e.target.value=''}};
 return <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_360px]">
  <div className="overflow-hidden rounded-2xl border border-border"><div className="flex flex-wrap gap-2 border-b border-border p-4"><input className={input} placeholder="بحث في مجموعات الأسعار" value={q} onChange={e=>setQ(e.target.value)}/><button onClick={downloadTemplate} className="rounded-xl border border-accent-line px-3 py-2 text-xs font-black text-accent">تحميل قالب Excel</button>{can('can_erp_price_group_import')&&<label className="cursor-pointer rounded-xl bg-accent px-3 py-2 text-xs font-black text-black">استيراد Excel<input hidden type="file" accept=".xlsx,.xls,.csv" onChange={importFile}/></label>}{can('can_erp_price_group_export')&&<button onClick={exportRows} className="rounded-xl border border-accent-line px-3 py-2 text-xs font-black text-accent">تصدير Excel</button>}</div>
   <div className="overflow-x-auto"><table className="w-full min-w-[700px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">الاسم</th><th className="p-3">كود التطبيق</th><th className="p-3">الوصف</th><th className="p-3">الحالة</th><th className="p-3">إجراء</th></tr></thead><tbody>{pager.visible.map(r=><tr key={r.id} className="border-t border-border"><td className="p-3 font-black">{r.name}</td><td className="p-3 font-bold text-accent">{r.app_code}</td><td className="p-3">{r.description||'—'}</td><td className="p-3">{r.is_active?'نشط':'موقوف'}</td><td className="p-3 whitespace-nowrap">{can('can_erp_price_group_edit')&&<button className="ml-3 font-bold text-accent" onClick={()=>{setEdit(r.id);setForm({name:r.name,app_code:r.app_code,description:r.description||'',is_active:r.is_active})}}>تعديل</button>}{can('can_erp_price_group_toggle')&&<button className="font-bold text-danger" onClick={()=>toggle(r)}>{r.is_active?'إيقاف':'تفعيل'}</button>}</td></tr>)}</tbody></table></div><ListPagination {...pager}/></div>
  <form onSubmit={save} className="rounded-2xl border border-border p-4"><h3 className="mb-4 font-black">{edit?'تعديل مجموعة أسعار':'مجموعة أسعار جديدة'}</h3><div className="grid gap-3"><input className={input} placeholder="الاسم *" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><input className={input} disabled={!!edit} placeholder="كود التطبيق *" value={form.app_code} onChange={e=>setForm(f=>({...f,app_code:e.target.value}))}/><textarea className={input} rows="4" placeholder="الوصف" value={form.description} onChange={e=>setForm(f=>({...f,description:e.target.value}))}/><button disabled={busy||(!edit&&!can('can_erp_price_group_create'))||(edit&&!can('can_erp_price_group_edit'))} className="rounded-xl bg-accent px-4 py-3 font-black text-black disabled:opacity-40">{busy?'جارٍ الحفظ…':edit?'حفظ التعديل':'إنشاء المجموعة'}</button>{edit&&<button type="button" onClick={()=>{setEdit(null);setForm(blank)}} className="rounded-xl border border-border px-4 py-2 text-sm">إلغاء التعديل</button>}{msg&&<p className="text-xs font-bold text-accent">{msg}</p>}</div></form>
 </div>
}