import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import Button from './ui/Button';
import { downloadPartyTemplate, exportParties, importParties, parsePartyFile } from '../lib/partyImportExport';
import ListPagination,{useListPagination} from './ui/ListPagination';
import PartyPaymentsAdmin from './PartyPaymentsAdmin';
import PartyStatementAdmin from './PartyStatementAdmin';

const empty = { code:'', name:'', business_name:'', contact_name:'', phone:'', phone_alt:'', email:'', tax_number:'', address:'', notes:'', opening_balance:'0', is_active:true };

export default function SuppliersAdmin(){
  const [rows,setRows]=useState([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState(null); const [view,setView]=useState('list');
  const [search,setSearch]=useState(''); const [viewing,setViewing]=useState(null); const [accountBalance,setAccountBalance]=useState(0); const [cardTab,setCardTab]=useState('info'); const [importBusy,setImportBusy]=useState(false); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('');
  const load=async()=>{ const {data,error}=await supabase.from('suppliers').select('*').order('created_at',{ascending:false}); if(error) throw error; setRows(data||[]); };
  useEffect(()=>{ load().catch(e=>setMsg(e.message)); },[]);
  const shown=useMemo(()=>rows.filter(r=>`${r.code} ${r.name} ${r.phone||''} ${r.contact_name||''}`.toLowerCase().includes(search.toLowerCase())),[rows,search]);
  const pager=useListPagination(shown,[search]);
  const change=(k,v)=>setForm(f=>({...f,[k]:v}));
  const doImport=async(e)=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;setImportBusy(true);setMsg('');try{const items=await parsePartyFile(file);const r=await importParties('supplier',items);if(r.errors.length){setMsg(`لم يتم الاستيراد: ${r.errors.length} صف به أخطاء. أول خطأ: صف ${r.errors[0].row} — ${r.errors[0].error}`);return}await load();setMsg(`تم استيراد ${r.inserted} مورد بنجاح.`)}catch(x){setMsg(x.message)}finally{setImportBusy(false)}};
  const reset=()=>{setForm(empty);setEditing(null);}; const goList=()=>{reset();setView('list');window.scrollTo({top:0,behavior:'smooth'})}; const addNew=()=>{reset();setView('form');window.scrollTo({top:0,behavior:'smooth'})};
  const save=async(e)=>{e.preventDefault(); if(!form.name.trim()) return setMsg('اسم المورد مطلوب.'); setBusy(true);setMsg('');
    const autoCode=form.code.trim()||String(Math.max(999,...rows.map(r=>Number(r.code)||0))+1); const payload={...form,code:autoCode,name:form.name.trim(),business_name:form.business_name.trim()||null,opening_balance:Number(form.opening_balance||0)};
    const q=editing?supabase.from('suppliers').update(payload).eq('id',editing):supabase.from('suppliers').insert(payload);
    const {error}=await q; setBusy(false); if(error) return setMsg(error.message); await load(); setMsg(editing?'تم تحديث المورد.':'تم إضافة المورد.'); goList(); };
  const edit=r=>{setView('form');setEditing(r.id);setForm({code:r.code||'',name:r.name||'',business_name:r.business_name||'',contact_name:r.contact_name||'',phone:r.phone||'',phone_alt:r.phone_alt||'',email:r.email||'',tax_number:r.tax_number||'',address:r.address||'',notes:r.notes||'',opening_balance:String(r.opening_balance??0),is_active:r.is_active!==false});};
  const toggle=async r=>{const {error}=await supabase.from('suppliers').update({is_active:!r.is_active}).eq('id',r.id); if(error)return setMsg(error.message); await load();};
  const openCard=async r=>{setViewing(r);setCardTab('info');const {data}=await supabase.from('dues').select('amount,settled_amount,due_type,status').eq('party_type','supplier').eq('party_id',r.id).neq('status','cancelled');setAccountBalance((data||[]).reduce((a,d)=>a+(d.due_type==='payable'?1:-1)*(Number(d.amount||0)-Number(d.settled_amount||0)),Number(r.opening_balance||0)));};
  const input='w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
  return <div className="space-y-4">
    {view==='list'&&<div className="grid gap-4">
      <section className="overflow-hidden rounded-2xl border border-border bg-card">
        <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border p-4"><div><h3 className="font-black text-text">الموردون</h3><p className="text-xs text-muted">{rows.length} مورد مسجل</p></div><div className="flex flex-wrap gap-2"><button className="rounded-xl bg-accent px-3 py-2 text-xs font-black text-on-accent" onClick={addNew}>+ إضافة مورد جديد</button><button className="rounded-xl border border-border px-3 py-2 text-xs font-black" onClick={()=>downloadPartyTemplate('supplier')}>تحميل قالب</button><label className="cursor-pointer rounded-xl bg-accent px-3 py-2 text-xs font-black text-on-accent">{importBusy?'جارٍ الاستيراد…':'استيراد Excel'}<input type="file" accept=".xlsx,.xls,.csv" className="hidden" onChange={doImport}/></label><button className="rounded-xl border border-border px-3 py-2 text-xs font-black" onClick={()=>exportParties('supplier',rows)}>تصدير Excel</button></div><input className={`${input} max-w-xs`} placeholder="بحث بالاسم أو الكود أو الهاتف" value={search} onChange={e=>setSearch(e.target.value)}/></div>
        <div className="overflow-x-auto"><table className="w-full min-w-[650px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">الكود</th><th className="p-3">المورد</th><th className="p-3">الهاتف</th><th className="p-3">الرصيد الافتتاحي</th><th className="p-3">الحالة</th><th className="p-3">إجراء</th></tr></thead><tbody>{pager.visible.map(r=><tr key={r.id} className="border-t border-border"><td className="p-3 font-bold text-accent">{r.code}</td><td className="p-3"><button type="button" onClick={()=>openCard(r)} className="font-bold text-text underline-offset-4 hover:text-accent hover:underline">{r.name}</button><div className="text-xs text-muted">{r.contact_name||'—'}</div></td><td className="p-3 text-muted">{r.phone||'—'}</td><td className="p-3 num text-text">{Number(r.opening_balance||0).toLocaleString()}</td><td className="p-3"><button onClick={()=>toggle(r)} className={`rounded-full px-2.5 py-1 text-xs font-bold ${r.is_active?'bg-accent-soft text-accent':'bg-surface text-muted'}`}>{r.is_active?'نشط':'موقوف'}</button></td><td className="p-3"><button onClick={()=>edit(r)} className="font-bold text-accent">تعديل</button></td></tr>)}{shown.length===0&&<tr><td colSpan="6" className="p-8 text-center text-muted">لا يوجد موردون مطابقون.</td></tr>}</tbody></table></div><ListPagination {...pager}/>
      </section>
      </div>}
      {view==='form'&&<form onSubmit={save} className="mx-auto w-full max-w-3xl rounded-2xl border border-border bg-card p-4"><button type="button" onClick={goList} className="mb-3 text-xs font-black text-accent">← العودة إلى الموردين</button><div className="mb-4 flex items-center justify-between"><div><h3 className="font-black text-text">{editing?'تعديل المورد':'مورد جديد'}</h3><p className="text-xs text-muted">البيانات الأساسية للمورد</p></div>{editing&&<button type="button" onClick={reset} className="text-xs font-bold text-muted">إلغاء</button>}</div>
        <div className="grid gap-3"><input className={input} placeholder="كود المورد (اختياري — يولد تلقائيًا)" value={form.code} onChange={e=>change('code',e.target.value)}/><input className={input} placeholder="اسم المورد *" value={form.name} onChange={e=>change('name',e.target.value)}/><input className={input} placeholder="اسم النشاط" value={form.business_name} onChange={e=>change('business_name',e.target.value)}/><input className={input} placeholder="اسم مسؤول التواصل" value={form.contact_name} onChange={e=>change('contact_name',e.target.value)}/><div className="grid grid-cols-2 gap-2"><input className={input} placeholder="الهاتف" value={form.phone} onChange={e=>change('phone',e.target.value)}/><input className={input} placeholder="هاتف إضافي" value={form.phone_alt} onChange={e=>change('phone_alt',e.target.value)}/></div><input className={input} type="email" placeholder="البريد الإلكتروني" value={form.email} onChange={e=>change('email',e.target.value)}/><input className={input} placeholder="الرقم الضريبي" value={form.tax_number} onChange={e=>change('tax_number',e.target.value)}/><input className={input} placeholder="العنوان" value={form.address} onChange={e=>change('address',e.target.value)}/><input className={input} type="number" step="0.01" placeholder="الرصيد الافتتاحي" value={form.opening_balance} onChange={e=>change('opening_balance',e.target.value)}/><textarea className={`${input} min-h-20`} placeholder="ملاحظات" value={form.notes} onChange={e=>change('notes',e.target.value)}/><label className="flex items-center gap-2 text-sm font-bold text-text"><input type="checkbox" checked={form.is_active} onChange={e=>change('is_active',e.target.checked)}/> المورد نشط</label><Button disabled={busy} type="submit">{busy?'جارٍ الحفظ...':editing?'حفظ التعديل':'إضافة المورد'}</Button>{msg&&<p className="text-center text-xs font-bold text-accent">{msg}</p>}</div>
      </form>}
      {viewing&&<div className="fixed inset-0 z-[120] overflow-y-auto bg-black/75 p-4" onClick={()=>setViewing(null)}><div className="mx-auto my-8 max-w-4xl rounded-3xl border border-accent-line bg-card p-5" onClick={e=>e.stopPropagation()}><div className="flex items-start justify-between gap-3"><div><div className="text-xs text-muted">بيانات المورد</div><h2 className="text-xl font-black text-accent">{viewing.name}</h2><div className="text-sm text-muted">{viewing.phone||'بدون هاتف'}{viewing.business_name?` · ${viewing.business_name}`:''}</div></div><button onClick={()=>setViewing(null)} className="text-xl">✕</button></div><div className="mt-4 rounded-2xl border border-accent-line bg-accent-soft p-4"><div className="text-xs text-muted">صافي حساب المورد</div><div className="mt-1 text-xl font-black text-accent">{Math.abs(accountBalance).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})} <span className="text-xs">{accountBalance===0?'مسدد':accountBalance>0?'للمورد علينا':'لنا على المورد'}</span></div></div><div className="mt-3 flex flex-wrap gap-2"><button onClick={()=>setCardTab('pay')} className="rounded-xl bg-accent px-4 py-2 text-sm font-black text-on-accent">سداد دفعة</button><button onClick={()=>setCardTab('statement')} className="rounded-xl border border-border px-4 py-2 text-sm font-black">كشف حساب</button><button onClick={()=>{const r=viewing;setViewing(null);edit(r)}} className="rounded-xl border border-border px-4 py-2 text-sm font-black">تعديل البيانات</button></div>{cardTab==='pay'&&<div className="mt-4"><PartyPaymentsAdmin type="supplier" initialPartyId={viewing.id}/></div>}{cardTab==='statement'&&<div className="mt-4"><PartyStatementAdmin type="supplier" initialPartyId={viewing.id}/></div>}</div></div>}
  </div>;
}