import { useEffect, useMemo, useState } from 'react';
import { supabase } from '../lib/supabase';
import Button from './ui/Button';
import { useAllowedBranches } from '../hooks/useAllowedBranches';
import InvoiceQuickView from './InvoiceQuickView';
import FinancialMovementQuickView from './FinancialMovementQuickView';
import DocumentLink from './DocumentLink';

const empty={name:'',code:'',branch:'',opening_balance:'0',notes:'',is_active:true};
const input='w-full rounded-xl border border-border bg-surface px-3 py-2.5 text-sm text-text outline-none focus:border-accent';
const money=n=>Number(n||0).toLocaleString();
const iso=d=>d.toISOString().slice(0,10);
function rangeFor(k){
 const now=new Date(),d=new Date(now.getFullYear(),now.getMonth(),now.getDate()),from=new Date(d),to=new Date(d);
 if(k==='all')return['',''];
 if(k==='yesterday'){from.setDate(from.getDate()-1);to.setDate(to.getDate()-1)}
 if(k==='7'){from.setDate(from.getDate()-6)}
 if(k==='month'){from.setDate(1)}
 if(k==='prevmonth'){from.setMonth(from.getMonth()-1,1);to.setDate(0)}
 if(k==='365'){from.setDate(from.getDate()-364)}
 return[iso(from),iso(to)];
}
export default function TreasuriesAdmin(){
 const {branches,canAccessBranch}=useAllowedBranches();
 const [rows,setRows]=useState([]),[moves,setMoves]=useState([]),[form,setForm]=useState(empty),[editing,setEditing]=useState(null),[msg,setMsg]=useState(''),[busy,setBusy]=useState(false),[uiView,setUiView]=useState('list'),[ledgerTreasury,setLedgerTreasury]=useState(null);
 const [period,setPeriod]=useState('all'),[from,setFrom]=useState(''),[to,setTo]=useState(''),[page,setPage]=useState(1),[docView,setDocView]=useState(null),[movementView,setMovementView]=useState(null);
 const load=async()=>{const [{data:r,error:e},{data:m,error:me}]=await Promise.all([supabase.from('treasuries').select('*').order('created_at',{ascending:false}),supabase.from('financial_movements').select('*').order('movement_date',{ascending:false}).order('created_at',{ascending:false})]);if(e)throw e;if(me)throw me;setRows((r||[]).filter(x=>!x.branch||canAccessBranch(x.branch)));setMoves(m||[])};
 useEffect(()=>{load().catch(e=>setMsg(e.message))},[]);
 const balances=useMemo(()=>{const b={};for(const r of rows)b[r.id]=Number(r.opening_balance||0);for(const m of moves){if(m.status==='cancelled')continue;const a=Number(m.amount||0);b[m.treasury_id]=(b[m.treasury_id]||0)+(m.movement_type==='receipt'||m.movement_type==='transfer_in'?a:-a)}return b},[rows,moves]);
 const save=async e=>{e.preventDefault();setMsg('');if(!form.name.trim()||!form.code.trim())return setMsg('اسم الخزينة والكود مطلوبان.');if(!form.branch)return setMsg('اختر الفرع.');if(!canAccessBranch(form.branch))return setMsg('ليس لديك صلاحية على هذا الفرع.');setBusy(true);try{const payload={...form,name:form.name.trim(),code:form.code.trim(),opening_balance:Number(form.opening_balance||0)};let q=editing?supabase.from('treasuries').update(payload).eq('id',editing).select().single():supabase.from('treasuries').insert(payload).select().single();const {data,error}=await q;if(error)throw error;if(!data?.id)throw Error('لم يتم إنشاء الخزينة. تحقق من صلاحية إنشاء الخزائن.');setForm(empty);setEditing(null);await load();setMsg(`تم ${editing?'تعديل':'إنشاء'} الخزينة بنجاح.`);setUiView('list')}catch(err){setMsg(`تعذر حفظ الخزينة: ${err.message}`)}finally{setBusy(false)}};
 const goList=()=>{setUiView('list');setEditing(null);setForm(empty);setLedgerTreasury(null);setMsg('')};
 const openLedger=t=>{setLedgerTreasury(t);setPeriod('all');setFrom('');setTo('');setPage(1);setUiView('ledger')};
 const setPreset=k=>{setPeriod(k);const[a,b]=rangeFor(k);setFrom(a);setTo(b);setPage(1)};
 const ledgerRows=useMemo(()=>moves.filter(m=>String(m.treasury_id)===String(ledgerTreasury?.id)&&(!from||m.movement_date>=from)&&(!to||m.movement_date<=to)),[moves,ledgerTreasury,from,to]);
 const pages=Math.max(1,Math.ceil(ledgerRows.length/20)),visible=ledgerRows.slice((page-1)*20,page*20);
 const movementLabel=x=>({receipt:'قبض',payment:'صرف',transfer_in:'تحويل وارد',transfer_out:'تحويل صادر'}[x]||x);
 return <div className="space-y-4">
  {docView&&<InvoiceQuickView type={docView.type} invoiceId={docView.id} onClose={()=>setDocView(null)}/>}
  {movementView&&<FinancialMovementQuickView movementId={movementView} onClose={()=>setMovementView(null)}/>}
  {uiView==='list'&&<><div className="flex flex-wrap items-center justify-between gap-2"><div>{msg&&<p className="text-xs font-bold text-accent">{msg}</p>}</div><button type="button" onClick={()=>{setForm(empty);setEditing(null);setMsg('');setUiView('form')}} className="rounded-xl bg-accent px-4 py-2 text-sm font-black text-on-accent">+ إضافة خزينة جديدة</button></div><section className="overflow-hidden rounded-2xl border border-border bg-card"><div className="border-b border-border p-4"><h3 className="font-black text-text">كل الخزائن المتاحة</h3><p className="text-xs text-muted">الرصيد الحالي = الرصيد الافتتاحي + المقبوضات والتحويلات الواردة − المدفوعات والتحويلات الصادرة.</p></div><div className="overflow-x-auto"><table className="w-full min-w-[760px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">الكود</th><th className="p-3">الخزينة</th><th className="p-3">الفرع</th><th className="p-3">الرصيد الحالي</th><th className="p-3">الحالة</th><th className="p-3">الإجراءات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t border-border"><td className="p-3 font-bold text-accent">{r.code}</td><td className="p-3 font-bold text-text">{r.name}</td><td className="p-3 text-muted">{r.branch||'—'}</td><td className="p-3 font-black text-text">{money(balances[r.id])}</td><td className="p-3">{r.is_active?'نشطة':'موقوفة'}</td><td className="p-3"><div className="flex flex-wrap gap-2"><button className="rounded-lg border border-border px-3 py-1.5 font-bold text-accent" onClick={()=>openLedger(r)}>دفتر الحسابات</button><button className="rounded-lg border border-border px-3 py-1.5 font-bold text-accent" onClick={()=>{setEditing(r.id);setMsg('');setUiView('form');setForm({name:r.name,code:r.code,branch:r.branch||'',opening_balance:String(r.opening_balance||0),notes:r.notes||'',is_active:r.is_active})}}>تعديل</button></div></td></tr>)}{!rows.length&&<tr><td colSpan="6" className="p-8 text-center text-muted">لا توجد خزائن بعد.</td></tr>}</tbody></table></div></section></>}
  {uiView==='form'&&<><button type="button" onClick={goList} className="rounded-xl border border-border px-4 py-2 text-sm font-black text-accent">← رجوع إلى كل الخزائن</button><form onSubmit={save} className="mx-auto w-full max-w-3xl rounded-2xl border border-border bg-card p-4"><h3 className="mb-4 font-black text-text">{editing?'تعديل الخزينة':'خزينة جديدة'}</h3><div className="grid gap-3"><input className={input} placeholder="اسم الخزينة *" value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/><input className={input} placeholder="كود الخزينة *" value={form.code} onChange={e=>setForm(f=>({...f,code:e.target.value}))}/><select className={input} value={form.branch} onChange={e=>setForm(f=>({...f,branch:e.target.value}))}><option value="">اختر الفرع *</option>{branches.map(b=><option key={b} value={b}>{b}</option>)}</select><input className={input} type="number" step="0.01" placeholder="الرصيد الافتتاحي" value={form.opening_balance} onChange={e=>setForm(f=>({...f,opening_balance:e.target.value}))}/><textarea className={input} placeholder="ملاحظات" value={form.notes} onChange={e=>setForm(f=>({...f,notes:e.target.value}))}/><label className="flex gap-2 text-sm font-bold text-text"><input type="checkbox" checked={form.is_active} onChange={e=>setForm(f=>({...f,is_active:e.target.checked}))}/> نشطة</label><Button type="submit" loading={busy} disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ الخزينة'}</Button>{msg&&<p className="rounded-xl border border-border p-3 text-xs font-bold text-accent">{msg}</p>}</div></form></>}
  {uiView==='ledger'&&ledgerTreasury&&<><div className="flex flex-wrap items-center justify-between gap-2"><button type="button" onClick={goList} className="rounded-xl border border-border px-4 py-2 text-sm font-black text-accent">← رجوع إلى كل الخزائن</button><div className="text-left"><h3 className="font-black text-text">دفتر حسابات — {ledgerTreasury.name}</h3><p className="text-xs text-muted">{ledgerTreasury.branch||'—'} · الرصيد الحالي {money(balances[ledgerTreasury.id])}</p></div></div>
   <section className="rounded-2xl border border-border bg-card p-4"><div className="mb-4 flex flex-wrap gap-2">{[['all','عرض الكل'],['today','اليوم'],['yesterday','الأمس'],['7','آخر 7 أيام'],['month','الشهر الحالي'],['prevmonth','الشهر الماضي'],['365','آخر 365 يوم'],['custom','نطاق مخصص']].map(([k,l])=><button key={k} type="button" onClick={()=>setPreset(k)} className={`rounded-xl border px-3 py-2 text-xs font-black ${period===k?'border-accent bg-accent text-black':'border-border text-text'}`}>{l}</button>)}</div>{period==='custom'&&<div className="mb-4 grid gap-2 sm:grid-cols-2"><label className="text-xs text-muted">من<input className={`${input} mt-1`} type="date" value={from} onChange={e=>{setFrom(e.target.value);setPage(1)}}/></label><label className="text-xs text-muted">إلى<input className={`${input} mt-1`} type="date" value={to} onChange={e=>{setTo(e.target.value);setPage(1)}}/></label></div>}
   <div className="overflow-x-auto"><table className="w-full min-w-[900px] text-right text-sm"><thead className="bg-surface text-xs text-muted"><tr><th className="p-3">التاريخ</th><th className="p-3">رقم القيد</th><th className="p-3">النوع</th><th className="p-3">الطرف</th><th className="p-3">المرجع</th><th className="p-3">وارد</th><th className="p-3">صادر</th><th className="p-3">الحالة</th><th className="p-3">ملاحظات</th></tr></thead><tbody>{visible.map(m=>{const incoming=m.movement_type==='receipt'||m.movement_type==='transfer_in';return <tr key={m.id} className="border-t border-border"><td className="p-3">{m.movement_date}</td><td className="p-3"><button type="button" onClick={()=>setMovementView(m.id)} className="font-bold text-accent underline underline-offset-4">{m.movement_number}</button></td><td className="p-3">{movementLabel(m.movement_type)}</td><td className="p-3">{m.party_name||'—'}</td><td className="p-3"><DocumentLink type={m.reference_type} id={m.reference_id} label={m.reference_type?`${m.reference_type} ${m.reference_id||''}`:'—'}/></td><td className="p-3 font-bold">{incoming?money(m.amount):'—'}</td><td className="p-3 font-bold">{!incoming?money(m.amount):'—'}</td><td className="p-3">{m.status==='cancelled'?'ملغي':'مرحّل'}</td><td className="p-3 text-muted">{m.notes||'—'}</td></tr>})}{!visible.length&&<tr><td colSpan="9" className="p-8 text-center text-muted">لا توجد قيود في الفترة المحددة.</td></tr>}</tbody></table></div>
   <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs"><span className="text-muted">{ledgerRows.length} قيد · حد أقصى 20 قيد لكل صفحة</span><div className="flex items-center gap-2"><button disabled={page<=1} onClick={()=>setPage(p=>Math.max(1,p-1))} className="rounded-lg border border-border px-3 py-2 disabled:opacity-40">السابق</button><span className="font-black">صفحة {page} من {pages}</span><button disabled={page>=pages} onClick={()=>setPage(p=>Math.min(pages,p+1))} className="rounded-lg border border-border px-3 py-2 disabled:opacity-40">التالي</button></div></div></section></>}
 </div>
}