-- ══════════════════════════════════════════════════════════════
--  V13.7.0 — كتالوج الموديلات المخصّصة + صلاحية إدارته
--
--  الفكرة: ملف الـCSV المدمج (phone_models_2017_2026) يفضل للقراءة
--  فقط للأبد. أي موديل يضيفه المستخدم بيتخزّن هنا في جدول مستقل،
--  فتحديث الـCSV مستقبلًا ما بيمسحش ولا بيدهس أي موديل يدوي.
--
--  البحث في الواجهة بيدمج المصدرين ويعرضهم كأنهم كتالوج واحد.
-- ══════════════════════════════════════════════════════════════

-- ── 1) الجدول ──────────────────────────────────────────────────
create table if not exists public.custom_phone_models (
  id          bigint generated by default as identity primary key,
  brand       text not null default '-',
  model       text not null,
  -- مفتاح مطبّع للمقارنة/منع التكرار: trim + lower + تقليص المسافات.
  -- عمود مُولّد → مستحيل يخرج عن التزامن مع model.
  model_key   text generated always as (
                lower(regexp_replace(btrim(model), '\s+', ' ', 'g'))
              ) stored,
  scope       text not null default 'global' check (scope in ('global','local')),
  branch_id   text,                       -- الفرع لما scope='local' (اسم الفرع النصّي)
  created_by  uuid default auth.uid(),
  created_at  timestamptz not null default now(),
  is_active   boolean not null default true
);

-- ── 2) منع التكرار (مطبّع) على الموديلات النشطة ────────────────
-- global: فريد على مستوى الكتالوج كله.
-- local : فريد داخل الفرع الواحد.
create unique index if not exists custom_phone_models_uniq_global
  on public.custom_phone_models (model_key)
  where is_active and scope = 'global';

create unique index if not exists custom_phone_models_uniq_local
  on public.custom_phone_models (model_key, branch_id)
  where is_active and scope = 'local';

create index if not exists custom_phone_models_brand_idx
  on public.custom_phone_models (brand) where is_active;

-- ── 3) صلاحية الإدارة (نفس نمط باقي الصلاحيات: عمود على roles) ──
alter table public.roles
  add column if not exists can_manage_custom_models boolean not null default true;
update public.roles set can_manage_custom_models = true where key = 'admin';

-- نظير على صف الموظف (للتوافق مع القراءة الخام لو الدور مش موجود)
alter table public.ishop_users
  add column if not exists can_manage_custom_models boolean;

-- ── 4) دالة السيرفر: هل المستخدم يقدر يدير الموديلات المخصّصة؟ ──
-- بتعكس محرّك الصلاحيات: الأدمن دايمًا، وإلا دلالة !== false، مع
-- أولوية علم الدور ثم علم الموظف.
create or replace function public.can_manage_custom_models()
returns boolean
language plpgsql
stable
security definer
set search_path to 'public'
as $$
declare
  u public.ishop_users%rowtype;
  role_flag boolean;
begin
  select * into u
    from public.ishop_users
   where auth_id = auth.uid() and is_active;
  if not found then return false; end if;
  if u.role = 'admin' then return true; end if;

  select case when r.is_admin then true
              else coalesce(r.can_manage_custom_models, true) end
    into role_flag
    from public.roles r
   where r.key = u.role;

  if role_flag is not null then
    return role_flag;
  end if;
  -- لا يوجد دور مطابق → نقرأ العمود على الموظف (null = مسموح)
  return coalesce(u.can_manage_custom_models, true);
end;
$$;

revoke all on function public.can_manage_custom_models() from public, anon;
grant execute on function public.can_manage_custom_models() to authenticated;

-- ── 5) الفرع الافتراضي للمستخدم الحالي (لتقييد الرؤية local) ────
create or replace function public.current_user_branch()
returns text
language sql
stable
security definer
set search_path to 'public'
as $$
  select branch from public.ishop_users
   where auth_id = auth.uid() and is_active
   limit 1;
$$;

revoke all on function public.current_user_branch() from public;
grant execute on function public.current_user_branch() to authenticated, anon;

-- ── 6) RLS ─────────────────────────────────────────────────────
alter table public.custom_phone_models enable row level security;

-- منع الأوامر الخطيرة على مستوى الجدول (زي devices)
revoke truncate, references, trigger on public.custom_phone_models from authenticated;
grant select, insert, update on public.custom_phone_models to authenticated;
grant select on public.custom_phone_models to anon;
grant usage, select on sequence public.custom_phone_models_id_seq to authenticated;

-- القراءة: الكل يشوف الـglobal؛ الموظف يشوف كمان موديلات فرعه.
drop policy if exists cpm_read_anon on public.custom_phone_models;
create policy cpm_read_anon
  on public.custom_phone_models for select to anon
  using (is_active and scope = 'global');

drop policy if exists cpm_read_auth on public.custom_phone_models;
create policy cpm_read_auth
  on public.custom_phone_models for select to authenticated
  using (
    is_active and (
      scope = 'global'
      or branch_id is not distinct from public.current_user_branch()
    )
  );

-- الإضافة: لمن يملك الصلاحية بس، والصف بيتنسب له.
drop policy if exists cpm_insert_auth on public.custom_phone_models;
create policy cpm_insert_auth
  on public.custom_phone_models for insert to authenticated
  with check (
    public.can_manage_custom_models()
    and (created_by is null or created_by = auth.uid())
    and (
      scope = 'global'
      or (scope = 'local' and branch_id is not distinct from public.current_user_branch())
    )
  );

-- التعديل (تفعيل/إلغاء تفعيل): لمن يملك الصلاحية.
drop policy if exists cpm_update_auth on public.custom_phone_models;
create policy cpm_update_auth
  on public.custom_phone_models for update to authenticated
  using (public.can_manage_custom_models())
  with check (public.can_manage_custom_models());
