-- V12 — user treasury access. Applied to production on 2026-07-27.
create table if not exists public.user_treasury_access (
  id bigint generated by default as identity primary key,
  user_id integer not null references public.ishop_users(id) on delete cascade,
  treasury_id bigint not null references public.treasuries(id) on delete cascade,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  unique (user_id, treasury_id)
);
create unique index if not exists user_treasury_access_one_default_per_user on public.user_treasury_access(user_id) where is_default=true;
alter table public.user_treasury_access enable row level security;
grant select,insert,update,delete on public.user_treasury_access to authenticated;
grant usage, select on sequence public.user_treasury_access_id_seq to authenticated;
